### ISSUE TITLE
Does not work with Mercurial largefiles

### ISSUE THREAD

**Issue by AnsisMalins** [scm-manager/scm-manager#1040]
Steps to reproduce:

1. Install Debian 9.12 in a VM
2. apt install mercurial openjdk-8-jre-headless
3. Enable the largefiles extension in /etc/mercurial/hgrc
4. wget and untar SCM Manager (tried both 1.60 and 2.0.0-rc5)
5. scm-manager/bin/scm-manager
6. In the web interface, enable HttpPostArgs, create a user, and create a Mercurial repository
7. Push from a large local Mercurial repository to the one in SCM Manager
8. Observe that the push stalls and the hg client hangs
9. Observe the following in the stdout of scm-manager (I copy-pasted the 2.0.0-rc5 version, but it looks similar for 1.60)

Server side Mercurial version: 4.0
Client side Mercurial version: 5.0.2 (TortoiseHg 5.0.2 on Windows 10)

```
2020-03-14 16:55:03.401 [cgi-pool-1] [          ] WARN  sonia.scm.web.cgi.DefaultCGIExecutor - Traceback (most recent call last):
  File "/root/.scm/lib/python/hgweb.py", line 61, in <module>
    wsgicgi.launch(application)
  File "/usr/lib/python2.7/dist-packages/mercurial/hgweb/wsgicgi.py", line 87, in launch
    for chunk in content:
  File "/usr/lib/python2.7/dist-packages/mercurial/hgweb/hgweb_mod.py", line 310, in run_wsgi
    for r in self._runwsgi(req, repo):
  File "/usr/lib/python2.7/dist-packages/mercurial/hgweb/hgweb_mod.py", line 350, in _runwsgi
    return protocol.call(rctx.repo, req, cmd)
  File "/usr/lib/python2.7/dist-packages/mercurial/hgweb/protocol.py", line 111, in call
    rsp = wireproto.dispatch(repo, p, cmd)
  File "/usr/lib/python2.7/dist-packages/mercurial/wireproto.py", line 575, in dispatch
    return func(repo, proto, *args)
  File "/usr/lib/python2.7/dist-packages/mercurial/wireproto.py", line 632, in batch
    op, args = pair.split(' ', 1)
ValueError: need more than 1 value to unpack

2020-03-14 16:55:03.403 [qtp1232367853-14] [BDRtE3DnD1H] ERROR sonia.scm.web.cgi.DefaultCGIExecutor - could not read from ServletInputStream and write to ProcessOutputStream
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at sonia.scm.util.IOUtil.copy(IOUtil.java:201)
        at sonia.scm.web.cgi.DefaultCGIExecutor.processServletInput(DefaultCGIExecutor.java:566)
        at sonia.scm.web.cgi.DefaultCGIExecutor.execute(DefaultCGIExecutor.java:414)
        at sonia.scm.web.cgi.DefaultCGIExecutor.execute(DefaultCGIExecutor.java:189)
        at sonia.scm.web.HgCGIServlet.process(HgCGIServlet.java:213)
        at sonia.scm.web.HgCGIServlet.handleRequest(HgCGIServlet.java:149)
        at sonia.scm.web.HgCGIServlet.service(HgCGIServlet.java:118)
        at sonia.scm.repository.spi.ScmProviderHttpServletDecorator.service(ScmProviderHttpServletDecorator.java:21)
        at sonia.scm.web.filter.PermissionFilter.service(PermissionFilter.java:125)
        at sonia.scm.web.HgPermissionFilter.service(HgPermissionFilter.java:73)
        at sonia.scm.repository.spi.InitializingHttpScmProtocolWrapper$ProtocolWrapper.serve(InitializingHttpScmProtocolWrapper.java:87)
        at sonia.scm.repository.spi.HttpScmProtocol.serve(HttpScmProtocol.java:34)
        at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:72)
        at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.noRedirect(RepositoryLegacyProtocolRedirectFilter.java:103)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.checkPathElements(RepositoryLegacyProtocolRedirectFilter.java:76)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.doFilter(RepositoryLegacyProtocolRedirectFilter.java:65)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter.doFilter(RepositoryLegacyProtocolRedirectFilter.java:47)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:102)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.MDCFilter.doFilter(MDCFilter.java:112)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:102)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.web.filter.AuthenticationFilter.processChain(AuthenticationFilter.java:301)
        at sonia.scm.web.filter.AuthenticationFilter.handleAuthentication(AuthenticationFilter.java:258)
        at sonia.scm.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:123)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:102)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:118)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:102)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1562)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:562)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:748)
2020-03-14 16:55:03.408 [qtp1232367853-14] [BDRtE3DnD1H] WARN  sonia.scm.web.HgCGIExceptionHandler - Mercurial/Python process ends with return code 1
```

**Comment by AnsisMalins** [comment]
I tried to put a simple `hg serve` behind an Nginx and ran into similar errors. I now believe that the probable root cause is that my particular repository blows past all HTTP header and body size limits set by servers. I had to raise Nginx's limits by orders of magnitude to get it to work. How can I try doing the same in SCM Manager?

What I had to change in Nginx:
```
client_max_body_size 20g; # Up from 1m
large_client_header_buffers 4 8m; # Up from 8k
proxy_buffering off; # Disabled to avoid writing gigabytes of temporary files
proxy_request_buffering off; # Disabled to avoid writing gigabytes of temporary files
proxy_read_timeout 600s; # Up from 60s
proxy_send_timeout 600s; # Up from 60s
```

**Comment by pfeuffer** [comment]
I tried to reproduce your failure, but haven't got it (I pushed a 26GB file). Maybe you can try it with docker, once? Just install docker and

```
docker run -p 8080:8080 -v scm-large-test:/var/lib/scm --name scm --rm scmmanager/scm-manager:2.0.0-rc5
```

Open http://localhost:8080/scm/repos/, login with scmadmin/scmadmin and create a hg repository. Then enable HttpPostArgs at http://localhost:8080/scm/admin/settings/hg

Enable largefiles in new repository:

```
docker exec -ti scm bash
echo "
[extensions]                                     
largefiles =
" >> /var/lib/scm/repositories/*/data/.hg/hgrc
```

And then push your repository to this new repository, eg.

```
hg push --all http://localhost:8080/scm/repo/scmadmin/hg
```

Don't forget to cleanup the docker volume after the test:

```
docker volume rm scm-large-test
```

Does this work? If not, more information about your repository would be great.

Regards

René

**Comment by AnsisMalins** [comment]
Just so you know, I intend to follow up on this soon(TM).

**Comment by apple314159** [comment]
I got it to work by explicitly creating the largefiles directory on the server. I had to find the repository location and create it: mkdir <reponame>/data/.hg/largefiles

**Comment by pfeuffer** [comment]
@apple314159 , did you have the same exception beforehand with the broken pipe? Or was it another issue?
