### ISSUE TITLE
Used cipher type in DefaultCipherHandler

### ISSUE THREAD

**Issue by chrswk** [scm-manager/scm-manager#1110]
Without knowing the reasons behind picking "AES/CTR/PKCS5PADDING", would it be possible to change to something that is supported out of the box in the latest Java version of [Cipher](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/javax/crypto/Cipher.html)?

```
Caused by: sonia.scm.security.CipherException: could not encode string
	at sonia.scm.security.DefaultCipherHandler.encode(DefaultCipherHandler.java:222)
	at sonia.scm.security.DefaultCipherHandler.storeKey(DefaultCipherHandler.java:247)
	at sonia.scm.security.DefaultCipherHandler.<init>(DefaultCipherHandler.java:132)
	at sonia.scm.security.CipherUtil.<init>(CipherUtil.java:62)
	at sonia.scm.security.CipherUtil.getInstance(CipherUtil.java:83)
	at sonia.scm.lifecycle.modules.BootstrapModule.configure(BootstrapModule.java:93)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 57 more
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CTR/PKCS5PADDING
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:573)
	at sonia.scm.security.DefaultCipherHandler.encode(DefaultCipherHandler.java:209)
	... 67 more
Caused by: javax.crypto.NoSuchPaddingException: CTR mode must be used with NoPadding
	at java.base/com.sun.crypto.provider.CipherCore.setPadding(CipherCore.java:299)
	at java.base/com.sun.crypto.provider.AESCipher.engineSetPadding(AESCipher.java:212)
	at java.base/javax.crypto.Cipher$Transform.setModePadding(Cipher.java:390)
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:566)
	... 68 more
```

Thanks
Chris

**Comment by sdorra** [comment]
Thanks @chrswk changing the used cipher should be easy, but i think we need a migration strategy for instances which have already encrypted data.

**Comment by chrswk** [comment]
Awesome, thanks. Looking forward to RC8.
