### ISSUE TITLE
Unable to migrate from 1.60 to 2.0.0 (too many open files)

### ISSUE THREAD

**Issue by Darkseal** [scm-manager/scm-manager#1177]
## Unable to migrate from 1.60 to 2.0.0 (too many open files)

I tried to migrate from 1.60 to 2.0.0: follower all instructions without issues up to the migration form (tried with COPY and MOVE - same result).

The migration fails, most likely due to the "too many open files" error described below. 

The issue occurs after processing successfully 10 HG repositories that seem to be migrated properly.

#### Describe how to reproduce the bug

I think it can be reproduced with any existing project with similar numbers than mine (~ 50 hg projects).

#### Describe your SCM-Manager setup

No special settings, using the standalone server on http://localhost:8080 and a local web browser (Mozilla Firefox).

#### Which operating system, browser and versions do you use?

Linux CentOS 7.3

#### Log of the bug

Here's what I can see in the `scm-manager.log` file (the actual project references have been replaced with <RepoNamespace> and <RepoName> for obvious reasons):

```
Caused by: java.nio.file.FileSystemException: /var/lib/scm/repositories/hg/RepoNamespace/RepoName/.hg/store/data/templates/yoo__venture/warp/systems/joomla/language/nb-_n_o/nb-_n_o.tpl__warp.ini.i: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:230)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at sonia.scm.update.repository.BaseMigrationStrategy.copyFile(BaseMigrationStrategy.java:79)
```

And here's the `scm-manager.err` file relevant content:

```
2020-06-08 12:53:30.819:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@7555b920{/,[file:///opt/scm-server/var/webapp/docroot/],AVAILABLE}
sonia.scm.server.ScmServerException: could not initialize server
	at sonia.scm.server.ScmServer.init(ScmServer.java:135)
	at sonia.scm.server.ScmServerDaemon.init(ScmServerDaemon.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:205)
Caused by: java.net.SocketException: Too many open files
	at sun.nio.ch.Net.socket0(Native Method)
	at sun.nio.ch.Net.serverSocket(Net.java:415)
	at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:85)
	at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
	at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:336)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	... 6 more
Cannot load daemon
Service exit with a return value of 3
```

Here's my `ulimit -a` report, I think it could be useful since the bug seems somewhat related to files not being closed by the migration process:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 200491
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 200491
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by pfeuffer** [comment]
This looks weird. The migration should be processed sequentially, one file after another. What JRE (Java vendor/version) are you using?

**Comment by pfeuffer** [comment]
Okay, the previous answer was rash. Maybe we have a leak here. But nonetheless your JRE is of interest, because we have successful migrations of bigger installations, already, and this has not been an issue before.

**Comment by pfeuffer** [comment]
And one more question due to a hint from Sebastian: Can you please check for the limits of the process? `ulimit -a` just lists the limits of the shell, not necessarilly those of the SCM-Manager. You can get the latter by calling `cat /proc/<process id>/limits`. The number of open files can be queried with `ls -1 /proc/<process id>/fd/ | wc`.
