### ISSUE TITLE
Migration Plan execution doesn't detect custom paths for repositories

### ISSUE THREAD

**Issue by bchanudet** [scm-manager/scm-manager#1193]
## Issue description

Hi! This is a follow-up from my [email sent to the mailing list](https://groups.google.com/forum/#!topic/scmmanager/-XrTP_yVMHA). I retried doing a migration from a 1.60 version to the 2.0 version currently available on the DEB package center.

Our repositories in 1.60 are stored in the folder `/home/scm/repos/(git|hg|svn)`, and it has been working well for us. I then upgraded the package to the version 2.0, and relaunched the service.

As expected, I was able to access the migration wizard, and configure the new namespaces and repository names for our 102 repositories. But when starting the migration, scm-manager crashes with a log saying it didn't find the original directory in /var/lib/scm/repositories for the first repository of the list.

#### Describe how to reproduce the bug

Install a 1.60 version from the DEB package center, setup the repositories folders to go to a custom location, like `/home/scm/repos` in my example. Create a repository, push something to it.

Then install the 2.0 version available on the DEB package center, start the migration wizard. It will find you repository. Type in a namespace and name for the repository, and launch the migration. 

Even though the migration wizard detected that the repository is in the custom folder, the execution of it will always look in `/var/lib/scm/repositories/` to find the original directory. It will throw an error and the server will return a 500 error to the browser.

I tested both COPY and MOVE strategies, both are throwing the same error.

#### Describe your SCM-Manager setup

The SCM Server is running on a Linux Debian 10 container hosted on Proxmox. No plugins were used on the 1.60 version prior to the migration.

#### Log of the bug

Information:
- `test-automation` is the first repository listed in `migration-plan.xml`
- `test-automation` is originally stored in `/home/scm/repos/git/test-automation/`

```
2020-06-16 15:07:37.153 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.repository.xml and version 2.0.0 (class sonia.scm.update.repository.XmlRepositoryV1UpdateStep)
2020-06-16 15:07:37.175 [main] [          ] INFO  sonia.scm.io.DefaultFileSystem - create directory /var/lib/scm/repositories/8iQxou3Vq1
2020-06-16 15:07:37.177 [main] [          ] INFO  sonia.scm.update.repository.MoveMigrationStrategy - moving repository data from /var/lib/scm/repositories/git/test-automation to /var/lib/scm/repositories/8iQxou3Vq1/data
2020-06-16 15:07:37.179 [main] [          ] ERROR sonia.scm.migration.UpdateException - could not read original directory
java.nio.file.NoSuchFileException: /var/lib/scm/repositories/git/test-automation
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at java.base/java.nio.file.Files.list(Files.java:3696)
        at sonia.scm.update.repository.BaseMigrationStrategy.listSourceDirectory(BaseMigrationStrategy.java:55)
        at sonia.scm.update.repository.MoveMigrationStrategy.moveData(MoveMigrationStrategy.java:86)
        at sonia.scm.update.repository.MoveMigrationStrategy.migrate(MoveMigrationStrategy.java:62)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.handleDataDirectory(XmlRepositoryV1UpdateStep.java:188)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.update(XmlRepositoryV1UpdateStep.java:161)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.lambda$doUpdate$0(XmlRepositoryV1UpdateStep.java:125)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.doUpdate(XmlRepositoryV1UpdateStep.java:122)
        at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
        at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
        at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
        at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
        at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
        at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
        at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
        at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
        at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
        at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:838)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at sonia.scm.server.ScmServer.init(ScmServer.java:130)
        at sonia.scm.server.ScmServerDaemon.init(ScmServerDaemon.java:110)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:205)
2020-06-16 15:07:37.180 [main] [          ] ERROR sonia.scm.migration.UpdateException - could not execute update for type sonia.scm.repository.xml to version 2.0.0 in class sonia.scm.update.repository.XmlRepositoryV1UpdateStep
sonia.scm.migration.UpdateException: could not read original directory
        at sonia.scm.update.repository.BaseMigrationStrategy.listSourceDirectory(BaseMigrationStrategy.java:57)
        at sonia.scm.update.repository.MoveMigrationStrategy.moveData(MoveMigrationStrategy.java:86)
        at sonia.scm.update.repository.MoveMigrationStrategy.migrate(MoveMigrationStrategy.java:62)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.handleDataDirectory(XmlRepositoryV1UpdateStep.java:188)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.update(XmlRepositoryV1UpdateStep.java:161)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.lambda$doUpdate$0(XmlRepositoryV1UpdateStep.java:125)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at sonia.scm.update.repository.XmlRepositoryV1UpdateStep.doUpdate(XmlRepositoryV1UpdateStep.java:122)
        at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
        at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
        at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
        at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
        at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
        at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
        at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
        at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
        at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
        at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:838)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at sonia.scm.server.ScmServer.init(ScmServer.java:130)
        at sonia.scm.server.ScmServerDaemon.init(ScmServerDaemon.java:110)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:205)
Caused by: java.nio.file.NoSuchFileException: /var/lib/scm/repositories/git/test-automation
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at java.base/java.nio.file.Files.list(Files.java:3696)
        at sonia.scm.update.repository.BaseMigrationStrategy.listSourceDirectory(BaseMigrationStrategy.java:55)
        ... 58 common frames omitted
```

#### Further information like screenshots

A few notes: 
- The strangest thing for me is that the migration wizard found all the repositories.
- Moving the original repos from `/home/scm/repos/` to `/var/lib/scm/repositories/` fixes the bug and the migration, once restarted, is going to completion. So there is a workaround and maybe this bug can be closed by saying "It only needs to be documented somewhere".
- I would be fine if the migration forces the new repositories to be placed in `/var/lib/scm/repositories/` without giving the ability to change the folder. Having them in /home/scm is coming from before we used scm-manager for all our DVCS repos. 
- I started to look into the code but not being a JAVA developer I'm not sure I can really help. I'll try to have a deeper look, but I would appreciate some insights. 

Thank you in advance

**Comment by pfeuffer** [comment]
Hi! You are right, the migration does not take the manual configuration into account. We will fix this soon.
