### ISSUE TITLE
windows git install, pushing simple change "rejected master -> master (unspecified reason)"

### ISSUE THREAD

**Issue by zenny6377** [scm-manager/scm-manager#1205]
## Issue description

from VS, while pushing a change, encountered the following error "Error encountered while pushing to the remote repository: rejected master -> master (unspecified reason)".. in the scm-manager.log there is the following stack trace:

#### Describe how to reproduce the bug

pushing changes from visual studio (getting latest changes works fine)

#### Describe your SCM-Manager setup

no proxy, running on windows box on VPN with other users, downloaded and installed today (so latest version of GIT and SCM)

#### Which operating system, browser and versions do you use?

windows server 2012 (where git and SCM are running), client is running Windows 10, VS 2019

#### Log of the bug

2020-06-17 16:29:10.884 [qtp1232367853-28] [B4S2CeAJ460] ERROR sonia.scm.web.GitReceiveHook - could not handle receive commands
java.lang.IllegalStateException: value is empty
	at sonia.scm.util.AssertUtil.assertIsNotEmpty(AssertUtil.java:60)
	at sonia.scm.repository.DefaultRepositoryManager.get(DefaultRepositoryManager.java:217)
	at sonia.scm.repository.DefaultRepositoryManager.get(DefaultRepositoryManager.java:71)
	at sonia.scm.repository.spi.HookEventFacade.handle(HookEventFacade.java:70)
	at sonia.scm.web.GitReceiveHook.handleReceiveCommands(GitReceiveHook.java:128)
	at sonia.scm.web.GitReceiveHook.onReceive(GitReceiveHook.java:162)
	at sonia.scm.web.GitReceiveHook.onPreReceive(GitReceiveHook.java:104)
	at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:2256)
	at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:2218)
	at org.eclipse.jgit.http.server.ReceivePackServlet.doPost(ReceivePackServlet.java:185)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:244)
	at org.eclipse.jgit.http.server.ReceivePackServlet$Factory.doFilter(ReceivePackServlet.java:147)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
	at org.eclipse.jgit.http.server.RepositoryFilter.doFilter(RepositoryFilter.java:145)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
	at org.eclipse.jgit.http.server.NoCacheFilter.doFilter(NoCacheFilter.java:86)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
	at org.eclipse.jgit.http.server.glue.UrlPipeline.service(UrlPipeline.java:221)
	at org.eclipse.jgit.http.server.glue.SuffixPipeline.service(SuffixPipeline.java:103)
	at org.eclipse.jgit.http.server.glue.MetaFilter.doFilter(MetaFilter.java:183)
	at org.eclipse.jgit.http.server.glue.MetaServlet.service(MetaServlet.java:142)
	at sonia.scm.web.ScmGitServlet.handleRegularGitRequest(ScmGitServlet.java:147)
	at sonia.scm.web.ScmGitServlet.service(ScmGitServlet.java:126)
	at sonia.scm.repository.spi.ScmProviderHttpServletDecorator.service(ScmProviderHttpServletDecorator.java:45)
	at sonia.scm.web.filter.PermissionFilter.service(PermissionFilter.java:116)
	at sonia.scm.repository.spi.InitializingHttpScmProtocolWrapper$ProtocolWrapper.serve(InitializingHttpScmProtocolWrapper.java:111)
	at sonia.scm.repository.spi.HttpScmProtocol.serve(HttpScmProtocol.java:58)
	at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:96)
	at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.noRedirect(RepositoryLegacyProtocolRedirectFilter.java:127)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.checkPathElements(RepositoryLegacyProtocolRedirectFilter.java:100)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.doFilter(RepositoryLegacyProtocolRedirectFilter.java:89)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter.doFilter(RepositoryLegacyProtocolRedirectFilter.java:71)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.filter.MDCFilter.doFilter(MDCFilter.java:105)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.web.filter.AuthenticationFilter.processChain(AuthenticationFilter.java:292)
	at sonia.scm.web.filter.AuthenticationFilter.handleAuthentication(AuthenticationFilter.java:249)
	at sonia.scm.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:114)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:109)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:745)

#### Further information like screenshots
![image](https://user-images.githubusercontent.com/67075840/84948460-c512bf80-b0b9-11ea-968c-6941044f82cc.png)

**Comment by pfeuffer** [comment]
Hi,

can you please have a look at the config file of your repository on the server? The repository should be stored in the scm home folder in `repositories/<some id>/data/config`. If you have multiple repositories, you can find the one in question by taking a look at the `repositories/<some id>/metadata.xml` file. There you can find the namespace and the name of the repository.

In the config file there should be an `scmm` part like this:

```
[scmm]
        repositoryid = 1dRzWjS904
```

The ID has to be the same like the repository folder name. If this part is missing, you can add it with a text editor.

_If_ this part is missing, can you please give us a hint how you created this repository (creted it inside SCM-Manager, upgraded it from an old version of SCM-Manager, copied the data somehow, whatsoever)? This would be of great help for us.

Thank you!

René

**Comment by zenny6377** [comment]
Hi Rene – thanks for the quick response – looks like this was indeed the issue.

 

We have been using CVS since the 90’s (for the same project) and I decided to convert it to GIT (preserving the history), I ended up creating an empty repo in SCM (not initializing it) and taking the converted repo files and copying them over to SCM.  I didn’t know about the tag you mentioned so it wouldn’t have existed in the converted repo data files.  I just tested a commit and it works.

 

Are there any other potential issues you can think of in doing it this way?  (as it relates to SCM)?

 

I did notice that after converting the history the user names are not aligned – i.e. “cramms” in the history in the git repo that was converted from CVS shows up in old commits whereas “Steve Cramm” appears in new commits even though his user name is cramms in SCM.  Maybe that’s a git issue

 

David Hrivnak

Prism Software Development Inc.

701 Boundary Road,  Ennismore, ON.

Canada  K0L 1T0

+1-416-457-7292

David.hrivnak@prismdevelopment.ca

**Comment by pfeuffer** [comment]
Hi David,

indeed this procedure is not really how it's intended. What you should have done is simply:

- create the repository in SCM-Manager
- go to your migrated repository and call `git push --all <git url>`, where the git url is the one from the information page in SCM-Manager.

As for your name issue: There may be an option in your conversion progress where you can map your user ids used in cvs to "real" names and email addresses used by git. We do not tamper with the names stored in the git commits and show them as they are, despite of what users are configured. So you should try to get your git repository right in the first place, so that you have a nice history.

Regards

René
