### ISSUE TITLE
configure ssl error

### ISSUE THREAD

**Issue by 1191149398** [scm-manager/scm-manager#1211]
scm version 2.1.0

configure ssl error

2020-06-22 16:11:43.693:INFO::main: Logging initialized @220ms to org.eclipse.jetty.util.log.StdErrLog
2020-06-22 16:11:44.055:WARN:oejx.XmlConfiguration:main: Config error at <Call name="addConnector"><Arg>|      <New class="org.eclipse.jetty.server.ssl.SslSelectChannelConnector"><Arg>|          <New class="org.eclipse.jetty.http.ssl.SslContextFactory"><Set name="excludeProtocols">|              <Array type="java.lang.String"><Item>SSLv2Hello</Item><Item>SSLv3</Item></Array>|            </Set></New>|        </Arg><Set name="Port">8181</Set><Set name="maxIdleTime">30000</Set><Set name="requestHeaderSize">16384</Set><Set name="keystore"><SystemProperty name="basedir" default="."/>/conf/keystore.jks</Set><Set name="password">topdisp</Set><Set name="keyPassword">topdisp</Set><Set name="truststore"><SystemProperty name="basedir" default="."/>/conf/keystore.jks</Set><Set name="trustPassword">topdisp</Set></New>|    </Arg></Call> java.lang.ClassNotFoundException: org.eclipse.jetty.server.ssl.SslSelectChannelConnector in file:///D:/document/Bill/Downloads/windows-2.1.0-app/scm-server/conf/server-config.xml
java.lang.ExceptionInInitializerError
Caused by: sonia.scm.server.ScmServerException: error during server configuration
	at sonia.scm.server.ScmServer.<init>(ScmServer.java:74)
	at sonia.scm.server.ScmServerDaemon.<clinit>(ScmServerDaemon.java:41)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.ssl.SslSelectChannelConnector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1027)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1561)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1462)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$600(XmlConfiguration.java:416)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1720)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1707)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:963)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:536)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:452)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:385)
	at sonia.scm.server.ScmServer.<init>(ScmServer.java:70)
	... 1 more
Exception in thread "main" 

![图片](https://user-images.githubusercontent.com/7444753/85265173-6d52ca80-b4a4-11ea-86e8-667561f1d8db.png)
jetty 9.4.30 not have  class org.eclipse.jetty.server.ssl.SslSelectChannelConnector

**Comment by pfeuffer** [comment]
Hi, you can find a working ssl config in out mailing list created by another user: https://groups.google.com/d/msg/scmmanager/9THwc9-POIE/olRJ7g6QAwAJ
Does this help?

**Comment by 1191149398** [comment]
thanks, It's working
