### ISSUE TITLE
inline migrate fails on security

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-manager#1219]
## Issue description

INLINE migration fails due to:
ERROR sonia.scm.migration.UpdateException - could not execute update for type sonia.scm.security.xml to version 2.0.1 in class sonia.scm.update.security.XmlSecurityV1UpdateStep
java.lang.NullPointerException: null

### Bug Report

2 bugs:
- cannot restart scm-server
- cannot migrate INLINE old 1.60 repositories

Please note:
dpkg -l |grep jre
ii  adoptopenjdk-8-hotspot-jre            8u252-b09-2                          amd64        OpenJDK Runtime Environment 8 (JRE) with Hotspot by AdoptOpenJDK
ii  default-jre                           2:1.11-71                            amd64        Standard Java or Java compatible Runtime
ii  default-jre-headless                  2:1.11-71                            amd64        Standard Java or Java compatible Runtime (headless)
ii  openjdk-11-jre:amd64                  11.0.7+10-3~deb10u1                  amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd64         11.0.7+10-3~deb10u1                  amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

But I assume this is not an issue as:
java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

#### Describe how to reproduce the bug

mv /var/lib/scm /var/lib/scm2
mkdir /var/lib/scm
copy files/dirs from home-dir of SCM 1.60 to /var/lib/scm  (1.60 SCM server is a different host, SCM 2 server is a fresh install on new server)
chown -R scm:scm /var/lib/scm
browse to scm url
select INLINE migration for all projects
issue on a terminal after some time manually 'service scm-server restart' as _scm-manager GUI cannot restart_ due to:
ERROR sonia.scm.lifecycle.PosixRestartStrategy - failed to collect java vm arguments
java.io.IOException: **Failed to exec 'jsvc.exec' No such file or directory**

the jsvc package is not(!) a **dependency**. But manually installing it does not fix this error.

when checking /var/log/scm/scm-server.out all seems ok after restart until the security.xml needs to be migrated.
End result: non functional scm-manager

**Note**: /var/log/scm/scm-manager.log and /var/log/scm/scm-server.out are (nearly?) identical?

#### Describe your SCM-Manager setup

SCM-manager behind a NGINX server using Let's Encrypt SSL certs

#### Which operating system, browser and versions do you use?

Debian 10 (buster), both on server and client. Browser: chromium from .deb repo: 80.0.3987.162-1~deb10u1

#### Log of the bug

2020-06-28 15:07:12.188 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.plugin.svn and version 2.0.0 (class sonia.scm.repository.SvnV2UpdateStep)
2020-06-28 15:07:12.199 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.plugin-center and version 2.0.0 (class sonia.scm.update.plugin.PluginCenterUpdateStep)
2020-06-28 15:07:12.215 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.user.xml and version 2.0.0 (class sonia.scm.update.user.XmlUserV1UpdateStep)
2020-06-28 15:07:12.215 [main] [          ] INFO  sonia.scm.update.user.XmlUserV1UpdateStep - moved old users file to /var/lib/scm/config/usersV1.xml
2020-06-28 15:07:12.215 [main] [          ] INFO  sonia.scm.update.user.XmlUserV1UpdateStep - moved old security file to /var/lib/scm/config/securityV1.xml
2020-06-28 15:07:12.275 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.git.lfs and version 2.0.0 (class sonia.scm.web.lfs.LfsV1UpdateStep)
2020-06-28 15:07:12.278 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.group.xml and version 2.0.0 (class sonia.scm.update.group.XmlGroupV1UpdateStep)
2020-06-28 15:07:12.279 [main] [          ] INFO  sonia.scm.update.group.XmlGroupV1UpdateStep - moved old groups file to /var/lib/scm/config/groupsV1.xml
2020-06-28 15:07:12.290 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.plugin.git and version 2.0.0 (class sonia.scm.repository.update.GitV2UpdateStep)
2020-06-28 15:07:15.532 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.security.xml and version 2.0.1 (class sonia.scm.update.security.XmlSecurityV1UpdateStep)
2020-06-28 15:07:15.556 [main] [          ] ERROR sonia.scm.migration.UpdateException - could not execute update for type sonia.scm.security.xml to version 2.0.1 in class sonia.scm.update.security.XmlSecurityV1UpdateStep
java.lang.NullPointerException: null
	at sonia.scm.update.security.XmlSecurityV1UpdateStep.mapV1Permissions(XmlSecurityV1UpdateStep.java:93)
	at sonia.scm.update.security.XmlSecurityV1UpdateStep.doUpdate(XmlSecurityV1UpdateStep.java:79)
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
	at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
	at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
	at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServerDaemon.init(ScmServerDaemon.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:205)
2020-06-28 15:07:15.557 [main] [          ] ERROR sonia.scm.lifecycle.BootstrapContextListener - failed to create stage two injector
sonia.scm.migration.UpdateException: could not execute update for type sonia.scm.security.xml to version 2.0.1 in class sonia.scm.update.security.XmlSecurityV1UpdateStep
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:90)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
	at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
	at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
	at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServerDaemon.init(ScmServerDaemon.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:205)
Caused by: java.lang.NullPointerException: null
	at sonia.scm.update.security.XmlSecurityV1UpdateStep.mapV1Permissions(XmlSecurityV1UpdateStep.java:93)
	at sonia.scm.update.security.XmlSecurityV1UpdateStep.doUpdate(XmlSecurityV1UpdateStep.java:79)
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
	... 49 common frames omitted

**Comment by sdorra** [comment]
Could you post your `/var/lib/scm/config/security.xml`?

**Comment by olaf7** [comment]
Sure:

**new security.xml file SCM-Manager2 after conversion**:
cat /var/lib/scm/config/security.xml 
<?xml version="1.0" ?>
<configuration>
  <entry>
    <key>abcdQQefgh</key>
    <value>
      <group-permission>false</group-permission>
      <name>scmadmin</name>
      <permission>
        <value>*</value>
      </permission>
    </value>
  </entry>
</configuration>

**security.xml file SCM-Manager 1.60 before conversion**:
cat /var/lib/scm2/config/security.xml 
<?xml version="1.0" ?>
<configuration>
  <entry>
    <key>qwertPPwxyz</key>
    <value>
      <group-permission>false</group-permission>
      <name>scmadmin</name>
      <permission>
        <value>*</value>
      </permission>
    </value>
  </entry>
</configuration>

**old security.xml file SCM-Manager2 after conversion**:
cat /var/lib/scm/config/securityV1.xml
<?xml version="1.0" ?>
<configuration>
</configuration>

**Note**: I adapted the keys before pasting. _Keys are different/unique_.

**Comment by sdorra** [comment]
@olaf7 could you create a separate issue for the restart problem?
