### ISSUE TITLE
Installation redmine plugin fails

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-manager#1237]
SCM-Manager 2.2.0 on Debian Buster (10 stable)

Installed readme plugin: success
Installed redmine plugin: not so much. See log

```
2020-07-03 18:04:08.273 [main] [          ] INFO  sonia.scm.lifecycle.BootstrapContextListener - start scm-manager initialization
2020-07-03 18:04:08.794 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - collect plugins
2020-07-03 18:04:09.004 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-readme-plugin
+- scm-legacy-plugin
+- scm-svn-plugin
+- scm-hg-plugin
+- scm-redmine-plugin
+- scm-git-plugin
+- scm-issuetracker-plugin
   +- scm-redmine-plugin

2020-07-03 18:04:09.942 [main] [          ] INFO  sonia.scm.update.repository.XmlRepositoryV1UpdateStep - no v1 repositories database file found
2020-07-03 18:04:10.270 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.redmine.config.global.xml and version 2.0.0 (class sonia.scm.redmine.update.RedmineV2GlobalConfigMigrationUpdateStep)
2020-07-03 18:04:10.317 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.redmine.config.repository.xml and version 2.0.0 (class sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep)
2020-07-03 18:04:10.340 [main] [          ] ERROR sonia.scm.migration.UpdateException - could not execute update for type sonia.scm.redmine.config.repository.xml to version 2.0.0 in class sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at sonia.scm.update.V1Properties.getOptional(V1Properties.java:61)
	at sonia.scm.update.V1Properties.getBoolean(V1Properties.java:65)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.buildConfig(RedmineV2ConfigMigrationUpdateStep.java:69)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.lambda$doUpdate$0(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.MapBasedPropertyReaderInstance.call(MapBasedPropertyReaderInstance.java:58)
	at sonia.scm.update.MapBasedPropertyReaderInstance.lambda$forEachEntry$0(MapBasedPropertyReaderInstance.java:44)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.MapBasedPropertyReaderInstance.forEachEntry(MapBasedPropertyReaderInstance.java:44)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.doUpdate(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
	at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
	at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
	at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServer.run(ScmServer.java:91)
	at sonia.scm.server.ScmServerDaemon.main(ScmServerDaemon.java:53)
2020-07-03 18:04:10.341 [main] [          ] ERROR sonia.scm.lifecycle.BootstrapContextListener - failed to create stage two injector
sonia.scm.migration.UpdateException: could not execute update for type sonia.scm.redmine.config.repository.xml to version 2.0.0 in class sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:90)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
	at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
	at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
	at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServer.run(ScmServer.java:91)
	at sonia.scm.server.ScmServerDaemon.main(ScmServerDaemon.java:53)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at sonia.scm.update.V1Properties.getOptional(V1Properties.java:61)
	at sonia.scm.update.V1Properties.getBoolean(V1Properties.java:65)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.buildConfig(RedmineV2ConfigMigrationUpdateStep.java:69)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.lambda$doUpdate$0(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.MapBasedPropertyReaderInstance.call(MapBasedPropertyReaderInstance.java:58)
	at sonia.scm.update.MapBasedPropertyReaderInstance.lambda$forEachEntry$0(MapBasedPropertyReaderInstance.java:44)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.MapBasedPropertyReaderInstance.forEachEntry(MapBasedPropertyReaderInstance.java:44)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.doUpdate(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
	... 45 common frames omitted

```

**Comment by pfeuffer** [comment]
You seem to have some interesting data on your side. Thanks for posting these issues! We will take a look at this one, too.

One little tip: You just have to delete the `scm-redmine-plugin` folder inside `plugins` in the scm-home to "uninstall" the plugin and you can go on with the next one.

**Comment by pfeuffer** [comment]
@olaf7 Can you please attach the file `scm-home/config/repository-properties-v1.xml` (maybe obfuscate concrete values like user, password and urls). Would be of great interest for us. Thank you!

**Comment by olaf7** [comment]
Here it is. All URLs, keys, email-addresses are indeed obfuscated.

```
<?xml version="1.0" ?>
<configuration>
  <entry>
    <key>9ZQKlvI401</key>
    <value>
      <item></item>
      <item>
        <key>redmine.url</key>
        <value>https://redmine.example.net/projects/r6</value>
      </item>
      <item>
        <key>redmine.auto-close-username-transformer</key>
        <value>{0}</value>
      </item>
      <item>
        <key>redmine.update-issues</key>
        <value>true</value>
      </item>
      <item>
        <key>git.default-branch</key>
        <value>master</value>
      </item>
      <item>
        <key>redmine.auto-close</key>
        <value>false</value>
      </item>
    </value>
  </entry>
  <entry>
    <key>1wPsrHPM81</key>
    <value>
      <item>
        <key>notify.contact.repository</key>
        <value>true</value>
      </item>
      <item>
        <key>redmine.auto-close-words</key>
        <value>fixed, fix, closed, close, resolved, resolve</value>
      </item>
      <item>
        <key>redmine.url</key>
        <value>https://redmine.example.net/projects/a2</value>
      </item>
      <item>
        <key>notify.max.diff.lines</key>
        <value></value>
      </item>
      <item>
        <key>redmine.auto-close-username-transformer</key>
        <value>{0}</value>
      </item>
      <item>
        <key>notify.contact.list</key>
        <value>me@example.com;</value>
      </item>
      <item>
        <key>redmine.update-issues</key>
        <value>true</value>
      </item>
      <item>
        <key>notify.email.per.push</key>
        <value>true</value>
      </item>
      <item>
        <key>notify.use.author.as.from.address</key>
        <value>true</value>
      </item>
      <item>
        <key>redmine.auto-close</key>
        <value>true</value>
      </item>
    </value>
  </entry>
  <entry>
    <key>EwOpgIgrh1</key>
    <value></value>
  </entry>
  <entry>
    <key>1hPp5dpYF1</key>
    <value>
      <item>
        <key>notify.contact.repository</key>
        <value>true</value>
      </item>
      <item>
        <key>redmine.auto-close-words</key>
        <value>fixed, fix, closed, close, resolved, resolve</value>
      </item>
      <item>
        <key>redmine.url</key>
        <value>https://redmine.example.net/projects/sc/</value>
      </item>
      <item>
        <key>notify.max.diff.lines</key>
        <value></value>
      </item>
      <item>
        <key>redmine.auto-close-username-transformer</key>
        <value>{0}</value>
      </item>
      <item>
        <key>notify.contact.list</key>
        <value>me@example.com;</value>
      </item>
      <item>
        <key>redmine.update-issues</key>
        <value>true</value>
      </item>
      <item>
        <key>notify.email.per.push</key>
        <value>true</value>
      </item>
      <item>
        <key>notify.use.author.as.from.address</key>
        <value>true</value>
      </item>
      <item>
        <key>redmine.auto-close</key>
        <value>true</value>
      </item>
    </value>
  </entry>
  <entry>
    <key>QNG0teQBD6</key>
    <value>
      <item></item>
      <item>
        <key>redmine.url</key>
        <value>https://redmine.example.net/projects/r</value>
      </item>
      <item>
        <key>redmine.auto-close-username-transformer</key>
        <value>{0}</value>
      </item>
      <item>
        <key>redmine.update-issues</key>
        <value>false</value>
      </item>
      <item>
        <key>redmine.auto-close</key>
      </item>
    </value>
  </entry>
  <entry>
    <key>2XVe2sMnt1</key>
    <value>
      <item>
        <key>redmine.url</key>
        <value>https://redmine.example.net/projects/mo</value>
      </item>
      <item>
        <key>redmine.auto-close-username-transformer</key>
        <value>{0}</value>
      </item>
      <item>
        <key>redmine.update-issues</key>
        <value>true</value>
      </item>
      <item>
        <key>redmine.auto-close</key>
        <value>true</value>
      </item>
    </value>
  </entry>
  <entry>
    <key>WlDszQtZj4</key>
    <value></value>
  </entry>
  <entry>
    <key>2nJpUR0N18</key>
    <value></value>
  </entry>
  <entry>
    <key>IKOcI4zfJ1</key>
    <value></value>
  </entry>
  <entry>
    <key>FmR8G6WmA2</key>
    <value></value>
  </entry>
</configuration>

```
