### ISSUE TITLE
SCM SSL problem

### ISSUE THREAD

**Issue by ruslanss-bob** [scm-manager/scm-manager#1250]
## Issue description

Problem launching SCM manager with SSL connector configured, binding to port works, certificate on ssl port is ok, scm application fails to start.

#### Describe how to reproduce the bug

Uncomment SSL related part in server-config.xml, add keystore file, configure jks file and its password. Restart SCM Manager, which fails to start, showing Internal Server Error.

#### Describe your SCM-Manager setup

Simple installation without reverse proxy and tomcat, SCM version 1.60 on RHEL7 and Oracle JDK 1.8.0_201

#### Which operating system, browser and versions do you use?

From any browser on Windows Server 2012R2 or Windows 10

#### Log of the bug
2020-07-10 11:52:31.329:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/scm,file:/opt/scm-server/work/webapp/},/opt/scm-server/var/webapp/scm-webapp.war
com.google.inject.ProvisionException: Guice provision errors:||1) Tried proxying sonia.scm.repository.api.RepositoryServiceFactory to support a circular dependency, but it is not an interface.|  at sonia.scm.ScmServletModule.configureServlets(ScmServletModule.java:367)|  while locating sonia.scm.repository.api.RepositoryServiceFactory|    for parameter 2 at sonia.scm.notify.FreemarkerContentBuilder.<init>(FreemarkerContentBuilder.java:96)|  while locating sonia.scm.notify.FreemarkerContentBuilder|  while locating sonia.scm.notify.ContentBuilder|    for parameter 0 at sonia.scm.notify.DefaultNotifyHandlerFactory.<init>(DefaultNotifyHandlerFactory.java:66)|  at sonia.scm.notify.DefaultNotifyHandlerFactory.class(DefaultNotifyHandlerFactory.java:66)|  while locating sonia.scm.notify.DefaultNotifyHandlerFactory|  while locating sonia.scm.notify.NotifyHandlerFactory|    for parameter 1 at sonia.scm.notify.NotifyRepositoryHook.<init>(NotifyRepositoryHook.java:85)|  at sonia.scm.notify.NotifyRepositoryHook.class(NotifyRepositoryHook.java:68)|  while locating sonia.scm.notify.NotifyRepositoryHook|  while locating sonia.scm.repository.RepositoryHook annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=10)|  at sonia.scm.plugin.ext.ExtensionBinder.bindMultiExtensionPoint(ExtensionBinder.java:180)|  while locating java.util.Set<sonia.scm.repository.RepositoryHook>|  at sonia.scm.repository.DefaultRepositoryManager.class(DefaultRepositoryManager.java:88)|  while locating sonia.scm.repository.DefaultRepositoryManager|  while locating sonia.scm.repository.RepositoryManager annotated with interface sonia.scm.Undecorated|  while locating sonia.scm.repository.RepositoryManagerProvider|  while locating sonia.scm.repository.RepositoryManager|    for parameter 2 at sonia.scm.repository.api.RepositoryServiceFactory.<init>(RepositoryServiceFactory.java:168)|  at sonia.scm.ScmServletModule.configureServlets(ScmServletModule.java:367)|  while locating sonia.scm.repository.api.RepositoryServiceFactory|    for parameter 0 at sonia.scm.statistic.StatisticManager.<init>(StatisticManager.java:98)|  at sonia.scm.plugin.ext.ExtensionBinder.bind(ExtensionBinder.java:133)|  while locating sonia.scm.statistic.StatisticManager|    for parameter 0 at sonia.scm.statistic.StatisticListener.<init>(StatisticListener.java:83)|  while locating sonia.scm.statistic.StatisticListener||1 error
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at sonia.scm.EagerSingletonModule.initialize(EagerSingletonModule.java:81)
        at sonia.scm.ScmContextListener.contextInitialized(ScmContextListener.java:145)
        at sonia.scm.boot.BootstrapListener.initializeContext(BootstrapListener.java:290)
        at sonia.scm.boot.BootstrapListener.contextInitialized(BootstrapListener.java:163)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:746)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:238)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1240)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:689)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:482)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:281)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at sonia.scm.server.ScmServer.init(ScmServer.java:146)
        at sonia.scm.server.ScmServerDaemon.init(ScmServerDaemon.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:205)

**Comment by LeoBolien** [comment]
Hello,
i have most likely the same configuration like @ruslanss-bob. If i try to start SCM Manager (with batch scm-server)
with activated SSL part in server-config.xml i get the error:

`Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: sonia.scm.server.ScmServerException: error during server configuration
        at sonia.scm.server.ScmServer.<init>(ScmServer.java:74)
        at sonia.scm.server.ScmServerDaemon.<clinit>(ScmServerDaemon.java:41)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.ssl.SslSelectChannelConnector
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.jmost likelyava:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1027)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1561)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1462)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$600(XmlConfiguration.java:416)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1720)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1707)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:963)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:536)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:452)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:385)
        at sonia.scm.server.ScmServer.<init>(ScmServer.java:70)`

I tried with java **jdk 1.8.0_212** and also with **jdk 11.0.7**, same error.
My **keystore.jks** file is valid. Starting without SSL enabled works. Any hints ?

I also tried the server-config.xml hint described in https://github.com/scm-manager/scm-manager/issues/1211
and https://groups.google.com/d/msg/scmmanager/9THwc9-POIE/olRJ7g6QAwAJ
but then i got the error:

`INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /scm, did not find org.eclipse.jetty.jsp.JettyJspServlet`

Thanks Leo

**Comment by sdorra** [comment]
```log
INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /scm, did not find org.eclipse.jetty.jsp.JettyJspServlet
```

Is just an information and means that /scm has no jsp support. But this is does not matter, because scm-manager does not use jsp at all.

To enable https with a jks keystore put the following snippet to the end of the `server-config.xml`:

```xml
<New id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory$Server">
  <Set name="KeyStorePath">
    <SystemProperty name="basedir" default="."/>/conf/keystore.jks
  </Set>
  <Set name="KeyStoreType">JKS</Set>
  <Set name="KeyStorePassword">secret</Set>

  <!-- TLS 1.3 requires Java 11 or higher -->
  <Set name="IncludeProtocols">
    <Array type="String">
        <Item>TLSv1.2</Item>
        <Item>TLSv1.3</Item>
    </Array>
  </Set>

  <Set name="IncludeCipherSuites">
    <Array type="String">
      <Item>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384</Item>
      <Item>TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384</Item>
      <Item>TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256</Item>
      <Item>TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256</Item>
      <Item>TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256</Item>
      <Item>TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256</Item>
      <Item>TLS_DHE_RSA_WITH_AES_256_GCM_SHA384</Item>
      <Item>TLS_DHE_RSA_WITH_AES_128_GCM_SHA256</Item>
    </Array>
  </Set>

  <Set name="useCipherSuitesOrder">
    <Property name="jetty.sslContext.useCipherSuitesOrder" default="false" />
  </Set>
</New>

<New id="sslHttpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
  <Arg>
    <Ref refid="httpConfig"/>
  </Arg>
  <Call name="addCustomizer">
    <Arg>
      <New class="org.eclipse.jetty.server.SecureRequestCustomizer">
        <Arg name="sniRequired" type="boolean"><Property name="jetty.ssl.sniRequired" default="false"/></Arg>
        <Arg name="sniHostCheck" type="boolean"><Property name="jetty.ssl.sniHostCheck" default="true"/></Arg>
        <Arg name="stsMaxAgeSeconds" type="int"><Property name="jetty.ssl.stsMaxAgeSeconds" default="-1"/></Arg>
        <Arg name="stsIncludeSubdomains" type="boolean"><Property name="jetty.ssl.stsIncludeSubdomains" default="false"/></Arg>
      </New>
    </Arg>
  </Call>
</New>

<Call name="addConnector">
  <Arg>
    <New id="sslConnector" class="org.eclipse.jetty.server.ServerConnector">
      <Arg name="server">
        <Ref refid="ScmServer" />
      </Arg>
      <Arg name="factories">
        <Array type="org.eclipse.jetty.server.ConnectionFactory">
          <Item>
            <New class="org.eclipse.jetty.server.SslConnectionFactory">
              <Arg name="next">http/1.1</Arg>
              <Arg name="sslContextFactory">
                <Ref refid="sslContextFactory"/>
              </Arg>
            </New>
          </Item>
          <Item>
            <New class="org.eclipse.jetty.server.HttpConnectionFactory">
              <Arg name="config">
                <Ref refid="sslHttpConfig" />
              </Arg>
            </New>
          </Item>
        </Array>
      </Arg>
      <Set name="host">
        <SystemProperty name="jetty.host" default="0.0.0.0" />
      </Set>
      <Set name="port">
        <Property name="jetty.ssl.port" default="8443" />
      </Set>
    </New>
  </Arg>
</Call>
```

The snippet assumes that the keystore is located at `conf/keystore.jks` and uses `secret` as password. SCM-Manager will open a second port on `8443` with enabled tls.

**Comment by sdorra** [comment]
The following snippet should work for SCM-Manager **1.x**:

```xml
<Call name="addConnector">
  <Arg>
    <New class="org.eclipse.jetty.server.ssl.SslSelectChannelConnector">
      <Arg>
        <New class="org.eclipse.jetty.http.ssl.SslContextFactory">

          <!-- TLS 1.3 requires Java 11 or higher -->
          <Set name="IncludeProtocols">
            <Array type="String">
                <Item>TLSv1</Item>
                <Item>TLSv1.1</Item>
                <Item>TLSv1.2</Item>
            </Array>
          </Set>

          <Set name="IncludeCipherSuites">
            <Array type="String">
              <Item>TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256</Item>
              <Item>TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256</Item>
              <Item>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384</Item>
              <Item>TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384</Item>
              <Item>TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256</Item>
              <Item>TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256</Item>
              <Item>TLS_DHE_RSA_WITH_AES_128_GCM_SHA256</Item>
              <Item>TLS_DHE_RSA_WITH_AES_256_GCM_SHA384</Item>
              <Item>TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256</Item>
              <Item>TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256</Item>
              <Item>TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256</Item>
              <Item>TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA</Item>
              <Item>TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA</Item>
              <Item>TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384</Item>
              <Item>TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384</Item>
              <Item>TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA</Item>
              <Item>TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA</Item>
              <Item>TLS_DHE_RSA_WITH_AES_128_CBC_SHA256</Item>
              <Item>TLS_DHE_RSA_WITH_AES_256_CBC_SHA256</Item>
              <Item>TLS_RSA_WITH_AES_128_GCM_SHA256</Item>
              <Item>TLS_RSA_WITH_AES_256_GCM_SHA384</Item>
              <Item>TLS_RSA_WITH_AES_128_CBC_SHA256</Item>
              <Item>TLS_RSA_WITH_AES_256_CBC_SHA256</Item>
              <Item>TLS_RSA_WITH_AES_128_CBC_SHA</Item>
              <Item>TLS_RSA_WITH_AES_256_CBC_SHA</Item>
              <Item>TLS_RSA_WITH_3DES_EDE_CBC_SHA</Item>
            </Array>
          </Set>

          <!--Set name="useCipherSuitesOrder">
            <Property name="jetty.sslContext.useCipherSuitesOrder" default="true" />
          </Set-->

        </New>
      </Arg>
      <Set name="Port">8181</Set>
      <Set name="maxIdleTime">30000</Set>
      <Set name="requestHeaderSize">16384</Set>
      <Set name="keystore"><SystemProperty name="basedir" default="." />/conf/keystore.jks</Set>
      <Set name="keystoreType">jks</Set>
      <Set name="password">secret</Set>
    </New>
  </Arg>
</Call>
```

**Comment by sdorra** [comment]
@ruslanss-bob the issue seams not related to the ssl configuration. It looks like a problem with the notification plugin. Does the problem persists, if you rename the plugins folder?

**Comment by ruslanss-bob** [comment]
> 
> 
> @ruslanss-bob the issue seams not related to the ssl configuration. It looks like a problem with the notification plugin. Does the problem persists, if you rename the plugins folder?

Looks like problem solved after update of used plugins! Thanks a lot!
