### ISSUE TITLE
Installing plugins fails

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-manager#1270]
On previous versions of SCM-Manager I could install various plugins including the Redmine one, so I am not sure if I should file this issue under SCM-Manager or under the Redmine plugin.

SCM-Manager 2.2.0 (.deb) on Debian Buster.
Log:
```
2020-07-29 16:32:18.923 [qtp1942406066-29] [F4S68mOjH1q] INFO  sonia.scm.plugin.PluginCenterLoader - fetch plugins from https://plugin-center-api.scm-manager.org/api/v1/plugins/2.2.0?os=Linux&arch=64
2020-07-29 16:34:05.698 [qtp1942406066-12] [88S68mqWS2B] INFO  sonia.scm.plugin.DefaultPluginManager - plugin scm-mail-plugin is already installed or installation is pending, skipping installation
2020-07-29 16:34:06.389 [ScmEventBus-1-0] [          ] WARN  sonia.scm.lifecycle.BootstrapContextFilter - received restart event from interface sonia.scm.plugin.PluginManager with reason: plugin installation
2020-07-29 16:34:06.391 [ScmEventBus-1-0] [          ] WARN  sonia.scm.lifecycle.RestartStrategy - destroy injection context
2020-07-29 16:34:06.391 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.modules.ResteasyAllInOneServletDispatcher - destroy resteasy
2020-07-29 16:34:06.466 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.BootstrapContextListener - shutdown scm-manager context
2020-07-29 16:34:06.468 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - remove cached attributes from context
2020-07-29 16:34:06.468 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - keep attribute com.google.inject.Injector in servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - keep attribute javax.servlet.context.tempdir in servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - keep attribute org.eclipse.jetty.util.DecoratedObjectFactory in servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - remove attribute org.apache.shiro.web.env.EnvironmentLoader.ENVIRONMENT_ATTRIBUTE_KEY from servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - keep attribute resourceCache in servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - remove attribute resteasy.deployments from servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - keep attribute org.eclipse.jetty.tmpdirConfigured in servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.ServletContextCleaner - keep attribute org.eclipse.jetty.server.Executor in servlet context
2020-07-29 16:34:06.469 [ScmEventBus-1-0] [          ] WARN  sonia.scm.repository.GitWorkQueueShutdownListener - shutdown jGit WorkQueue executor
2020-07-29 16:34:06.478 [ScmEventBus-1-0] [          ] INFO  sonia.scm.cache.GuavaCacheManager - close guava cache manager
2020-07-29 16:34:06.479 [ScmEventBus-1-0] [          ] INFO  sonia.scm.lifecycle.classloading.ClassLoaderLifeCycle - shutdown classloader infrastructure
2020-07-29 16:34:06.484 [ScmEventBus-1-0] [          ] WARN  sonia.scm.lifecycle.PosixRestartStrategy - restart scm-manager jvm process
2020-07-29 16:34:10.818 [main] [          ] INFO  sonia.scm.lifecycle.classloading.ClassLoaderLifeCycle - create new simple ClassLoaderLifeCycle
2020-07-29 16:34:10.822 [main] [          ] INFO  sonia.scm.lifecycle.BootstrapContextFilter - register for restart events
2020-07-29 16:34:10.827 [main] [          ] INFO  sonia.scm.event.LegmanScmEventBus - create new event bus ScmEventBus-1
2020-07-29 16:34:10.933 [main] [          ] INFO  sonia.scm.event.ScmEventBus - use sonia.scm.event.LegmanScmEventBus as event bus implementation
2020-07-29 16:34:11.061 [main] [          ] INFO  sonia.scm.lifecycle.BootstrapContextListener - start scm-manager initialization
2020-07-29 16:34:12.278 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - collect plugins
2020-07-29 16:34:13.084 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-readme-plugin
+- scm-notify-plugin
+- scm-activity-plugin
+- scm-mail-plugin
   +- scm-notify-plugin
+- scm-legacy-plugin
+- scm-svn-plugin
+- scm-hg-plugin
+- scm-redmine-plugin
+- scm-statistic-plugin
+- scm-git-plugin
+- scm-issuetracker-plugin
   +- scm-redmine-plugin

2020-07-29 16:34:14.838 [main] [          ] INFO  sonia.scm.update.repository.XmlRepositoryV1UpdateStep - no v1 repositories database file found
2020-07-29 16:34:15.408 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.statistic.data.xml and version 2.0.0 (class sonia.scm.statistic.update.V1StatisticUpdateStep)
2020-07-29 16:34:15.496 [main] [          ] INFO  sonia.scm.update.UpdateEngine - running update step for type sonia.scm.redmine.config.repository.xml and version 2.0.0 (class sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep)
2020-07-29 16:34:15.530 [main] [          ] ERROR sonia.scm.migration.UpdateException - could not execute update for type sonia.scm.redmine.config.repository.xml to version 2.0.0 in class sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at sonia.scm.update.V1Properties.getOptional(V1Properties.java:61)
	at sonia.scm.update.V1Properties.getBoolean(V1Properties.java:65)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.buildConfig(RedmineV2ConfigMigrationUpdateStep.java:69)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.lambda$doUpdate$0(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.MapBasedPropertyReaderInstance.call(MapBasedPropertyReaderInstance.java:58)
	at sonia.scm.update.MapBasedPropertyReaderInstance.lambda$forEachEntry$0(MapBasedPropertyReaderInstance.java:44)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.MapBasedPropertyReaderInstance.forEachEntry(MapBasedPropertyReaderInstance.java:44)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.doUpdate(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
	at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
	at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
	at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServer.run(ScmServer.java:91)
	at sonia.scm.server.ScmServerDaemon.main(ScmServerDaemon.java:53)
2020-07-29 16:34:15.531 [main] [          ] ERROR sonia.scm.lifecycle.BootstrapContextListener - failed to create stage two injector
sonia.scm.migration.UpdateException: could not execute update for type sonia.scm.redmine.config.repository.xml to version 2.0.0 in class sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:90)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
	at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
	at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
	at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServer.run(ScmServer.java:91)
	at sonia.scm.server.ScmServerDaemon.main(ScmServerDaemon.java:53)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at sonia.scm.update.V1Properties.getOptional(V1Properties.java:61)
	at sonia.scm.update.V1Properties.getBoolean(V1Properties.java:65)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.buildConfig(RedmineV2ConfigMigrationUpdateStep.java:69)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.lambda$doUpdate$0(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.MapBasedPropertyReaderInstance.call(MapBasedPropertyReaderInstance.java:58)
	at sonia.scm.update.MapBasedPropertyReaderInstance.lambda$forEachEntry$0(MapBasedPropertyReaderInstance.java:44)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at sonia.scm.update.MapBasedPropertyReaderInstance.forEachEntry(MapBasedPropertyReaderInstance.java:44)
	at sonia.scm.redmine.update.RedmineV2ConfigMigrationUpdateStep.doUpdate(RedmineV2ConfigMigrationUpdateStep.java:61)
	at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
	... 45 common frames omitted

```

**Comment by sdorra** [comment]
This is same issue as #1237, which is fixed with SCM-Manager 2.3.0. The plugin installation should work with 2.3.0.
