### ISSUE TITLE
Webhook plugin upgrade failed

### ISSUE THREAD

**Issue by schneidr** [scm-manager/scm-manager#1280]
## Issue description

Reenabling the webhook plugin after upgrading SCM-Manager to 2.x causes an exception and the server fails to start.

#### Describe how to reproduce the bug

After upgrading SCM-Manager from 1.60 to 2.x I reinstalled the webhook plugin, that I had installed before. After the restart of the server it fails with the exception:

> could not execute update for type sonia.scm.webhook.config.repository.xml to version 2.0.0 in class sonia.scm.webhook.update.WebhooksV2ConfigMigrationUpdateSte

#### Describe your SCM-Manager setup

What plugins and what versions do you use? Are you using a server like tomcat? Do you have special settings like proxies? Are you running your instance behind a reverse proxy?

- The server is running in the official Docker container (Version 2.3)
- The server is running behind an Apache revesrse proxy.

Plugins in use:

- scm-activity-plugin
- scm-authormapping-plugin
- scm-branchwp-plugin
- scm-el-plugin
- scm-git-plugin
- scm-hg-plugin
- scm-landingpage-plugin
- scm-ldap-plugin
- scm-legacy-plugin
- scm-mail-plugin
- scm-notify-plugin
- scm-pathwp-plugin
- scm-readme-plugin
- scm-review-plugin
- scm-statistic-plugin
- scm-svn-plugin
- scm-webhook-plugin

#### Which operating system, browser and versions do you use?

Windows 10, Chrome 83

#### Log of the bug

            sonia.scm.migration.UpdateException: could not execute update for type sonia.scm.webhook.config.repository.xml to version 2.0.0 in class sonia.scm.webhook.update.WebhooksV2ConfigMigrationUpdateStep
        at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:90)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at sonia.scm.update.UpdateEngine.update(UpdateEngine.java:77)
        at sonia.scm.lifecycle.BootstrapContextListener.processUpdates(BootstrapContextListener.java:175)
        at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:133)
        at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
        at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
        at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
        at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
        at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
        at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
        at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:408)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at sonia.scm.server.ScmServer.init(ScmServer.java:130)
        at sonia.scm.server.ScmServer.run(ScmServer.java:91)
        at sonia.scm.server.ScmServerDaemon.main(ScmServerDaemon.java:53)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at sonia.scm.webhook.update.WebhooksV2ConfigMigrationUpdateStep.createWebHook(WebhooksV2ConfigMigrationUpdateStep.java:98)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at sonia.scm.webhook.update.WebhooksV2ConfigMigrationUpdateStep.buildConfig(WebhooksV2ConfigMigrationUpdateStep.java:87)
        at sonia.scm.webhook.update.WebhooksV2ConfigMigrationUpdateStep.lambda$doUpdate$1(WebhooksV2ConfigMigrationUpdateStep.java:70)
        at sonia.scm.update.MapBasedPropertyReaderInstance.call(MapBasedPropertyReaderInstance.java:58)
        at sonia.scm.update.MapBasedPropertyReaderInstance.lambda$forEachEntry$0(MapBasedPropertyReaderInstance.java:44)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at sonia.scm.update.MapBasedPropertyReaderInstance.forEachEntry(MapBasedPropertyReaderInstance.java:44)
        at sonia.scm.webhook.update.WebhooksV2ConfigMigrationUpdateStep.doUpdate(WebhooksV2ConfigMigrationUpdateStep.java:69)
        at sonia.scm.update.UpdateEngine.execute(UpdateEngine.java:87)
        ... 45 more

**Comment by schneidr** [comment]
Probably related to #1235

**Comment by pfeuffer** [comment]
Thanks for the report, @schneidr . This looks like a different issue.

I've taken the liberty to copy your issue to scm-manager/scm-webhook-plugin#11 to track it directly with the plugin. Therefore I will close this issue.

In your scm home folder you should have a file `config/repository-properties-v1.xml`. Can you send us this one or at least the part that is related to `webhooks` (should be mentioned as a key at least once).

Thank you for your support.

**Comment by pfeuffer** [comment]
Damn it -- only just now found the feature to transfer an issue. Will do this next time...
