### ISSUE TITLE
install mail plus ,failed, server can't started.

### ISSUE THREAD

**Issue by chenhao86** [scm-manager/scm-manager#1292]
when i install mail plus,not install succ, then start server err. see below information.

sonia.scm.plugin.PluginNotInstalledException: dependency scm-mail-plugin of scm-notify-plugin is not installed
	at sonia.scm.plugin.SmpNodeBuilder.lambda$assertDependenciesFulfilled$3(SmpNodeBuilder.java:77)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at sonia.scm.plugin.SmpNodeBuilder.assertDependenciesFulfilled(SmpNodeBuilder.java:74)
	at sonia.scm.plugin.SmpNodeBuilder.lambda$buildNodeTree$0(SmpNodeBuilder.java:41)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at sonia.scm.plugin.SmpNodeBuilder.buildNodeTree(SmpNodeBuilder.java:41)
	at sonia.scm.plugin.PluginTree.<init>(PluginTree.java:84)
	at sonia.scm.plugin.PluginProcessor.collectPlugins(PluginProcessor.java:183)
	at sonia.scm.plugin.PluginsInternal.collectPlugins(PluginsInternal.java:89)
	at sonia.scm.lifecycle.PluginBootstrap.collectPlugins(PluginBootstrap.java:108)
	at sonia.scm.lifecycle.PluginBootstrap.<init>(PluginBootstrap.java:79)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:115)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:134)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServer.run(ScmServer.java:91)
	at sonia.scm.server.ScmServerDaemon.main(ScmServerDaemon.java:53)

**Comment by sdorra** [comment]
Have you used the plugins tap inside of scm-manager to install the plugins or have you installed the plugins manually (copy the smp files into the plugins folder)?

**Comment by chenhao86** [comment]
used the plugins tap inside of scm-manager to install the plugins  on windows

**Comment by sdorra** [comment]
Which version of SCM-Manager do you use and which plugin have you tried to install?

**Comment by chenhao86** [comment]
scm-manager: windows-2.3.1-app
plug is from tap inside of sc-manager.notify 2.0.1

**Comment by chenhao86** [comment]
on windows  , where is plugin path , where is code path? i can't find those paths in the scm-manager directory.

**Comment by sdorra** [comment]
https://scm-manager.org/docs/2.3.x/en/installation/windows/#home-directory

**Comment by sdorra** [comment]
I can't reproduce the installation failure. Do you have an corporate firewall, virus scanner or proxy between scm-manager and the internet? Could you try to install another plugin? Please try the support plugin.

**Comment by chenhao86** [comment]
3Q. i try to delete all config and reinstall sc-manager .

**Comment by chenhao86** [comment]
i reinstall sc-manager. maybe plugin conflict each other.
install thoese plugin:

scm-mail-plugin
scm-activity-plugin
scm-readme-plugin

then server can't start.

**Comment by sdorra** [comment]
Could you please post the error?

**Comment by sdorra** [comment]
The full log would be better than only the error. Could you please post the whole log file?

**Comment by chenhao86** [comment]
ok .i send mail to your gmail.please care it.

**Comment by sdorra** [comment]
After studying the logs i can see the initial error you posted. But after that i can see a bunch of plugin installation and restarts without errors.

What is the effect of the error? Is the site not reachable?
