### ISSUE TITLE
Internal 500 Error on Branch Commit History on Mercurial Repository

### ISSUE THREAD

**Issue by mperyer1** [scm-manager/scm-manager#1446]
## Issue description

I'm currently setting up a new scm-manager 2.10 Server to use with mercurial, I'm currently manually migrating mercurial repositories from an older version of scm-manager.

On a Repository that has been pushed to with existing mercurial data viewing the commit history returns an internal 500 error - see attached image.

Note: The repositories are being migrated from scm-manager 1.35 using the mercurial commandline. As written in: https://www.scm-manager.org/docs/2.9.x/en/import/

#### Describe how to reproduce the bug

View the Commit History of a Branch in Mercurial Repositories after using the mercurial commandline (hg) to push repo data from scm-manager 1.35

#### Describe your SCM-Manager setup

Plugins in use:
- LDAP 2.0.1
- SSH 2.2.1
- Activity 2.0.0
- Statistic 2.0.0
- Cockpit 2.0.0
- Legacy 2.10.0
- Rest 2.0.0
- Mail 2.3.0
- Git 2.10.0
- Mercurial 2.10.0
- Subversion 2.10.0

There are no Proxy Settings and the Server is not sat behind a Reverse Proxy.

The scm-manager server is using the default web engine from the YUM Repository.

#### Which operating system, browser and versions do you use?

scm-manager is installed on a CentOS Linux release 7.9.2009 (Core) VM

I'm currently working on it from a Windows 10 PC with Google Chrome Version 86.0.4240.183.

#### Log of the bug

`2020-11-25 07:07:55.218 [qtp670576685-15] [8sSHM0al62P] WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected java.lang.IllegalStateException to status code 500
java.lang.IllegalStateException: Server pool is stopped
	at com.aragost.javahg.internals.ServerPool.take(ServerPool.java:148)
	at com.aragost.javahg.internals.AbstractCommand.launchStream(AbstractCommand.java:166)
	at com.aragost.javahg.commands.LogCommand.execute(LogCommand.java:86)
	at com.aragost.javahg.Changeset.ensureAllDataLoaded(Changeset.java:333)
	at com.aragost.javahg.Changeset.getTimestamp(Changeset.java:271)
	at sonia.scm.repository.spi.HgTagsCommand$TagTransformer.apply(HgTagsCommand.java:102)
	at sonia.scm.repository.spi.HgTagsCommand$TagTransformer.apply(HgTagsCommand.java:87)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sonia.scm.repository.Tags.getTagByName(Tags.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at sonia.scm.api.v2.resources.DefaultChangesetToChangesetDtoMapper.getListOfObjects(DefaultChangesetToChangesetDtoMapper.java:154)
	at sonia.scm.api.v2.resources.DefaultChangesetToChangesetDtoMapper.createDto(DefaultChangesetToChangesetDtoMapper.java:131)
	at sonia.scm.api.v2.resources.DefaultChangesetToChangesetDtoMapperImpl.map(DefaultChangesetToChangesetDtoMapperImpl.java:28)
	at sonia.scm.api.v2.resources.ChangesetCollectionToDtoMapperBase.lambda$map$0(ChangesetCollectionToDtoMapperBase.java:47)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at sonia.scm.api.v2.resources.PagedCollectionToDtoMapper.map(PagedCollectionToDtoMapper.java:57)
	at sonia.scm.api.v2.resources.ChangesetCollectionToDtoMapperBase.map(ChangesetCollectionToDtoMapperBase.java:47)
	at sonia.scm.api.v2.resources.ChangesetCollectionToDtoMapperBase.map(ChangesetCollectionToDtoMapperBase.java:51)
	at sonia.scm.api.v2.resources.BranchChangesetCollectionToDtoMapper.map(BranchChangesetCollectionToDtoMapper.java:44)
	at sonia.scm.api.v2.resources.BranchRootResource.history(BranchRootResource.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.noRedirect(RepositoryLegacyProtocolRedirectFilter.java:127)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.checkPathElements(RepositoryLegacyProtocolRedirectFilter.java:100)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.doFilter(RepositoryLegacyProtocolRedirectFilter.java:89)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter.doFilter(RepositoryLegacyProtocolRedirectFilter.java:71)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.filter.MDCFilter.doFilter(MDCFilter.java:105)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.web.security.TokenRefreshFilter.doFilter(TokenRefreshFilter.java:78)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.web.filter.AuthenticationFilter.processChain(AuthenticationFilter.java:264)
	at sonia.scm.web.filter.AuthenticationFilter.handleAuthentication(AuthenticationFilter.java:223)
	at sonia.scm.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:107)
	at sonia.scm.web.security.ApiAuthenticationFilter.doFilter(ApiAuthenticationFilter.java:99)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.security.TokenExpiredFilter.doFilter(TokenExpiredFilter.java:66)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:109)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
`

#### Further information like screenshots
![image](https://user-images.githubusercontent.com/75020392/100226148-3a12dc80-2f17-11eb-8580-2c1aa6c2a55f.png)

**Comment by sdorra** [comment]
It looks like the Mercurial process crashed while loading the tags. Do we have any chance to get a copy of that repository?

**Comment by mperyer1** [comment]
I have done some more digging and found the following:
1. We have 78 Mercurial Repositories being migrated, but only the repositories with tags have the issue
2. Creating a Test Repository on the hg commandline and migrating it across has no issues - no tags generated

I added Tags to the TEST Repo and pushed to the new repo - doing so recreated the issue.

I've attached a copy of the TEST Repo i recreated the issue in:
[TEST.tar.gz](https://github.com/scm-manager/scm-manager/files/5615611/TEST.tar.gz)

**Comment by sdorra** [comment]
This issue is really strange, because the error seems only to occur if the commit listing is opened first. If we first select tags and then commits, all worked as expected.

However we were able to reproduce the issue and working on a fix, see #1457 for more details.

Thank you very much for your debugging and the test repository.

**Comment by sdorra** [comment]
The fix will be released with the next SCM-Manager version.

**Comment by sdorra** [comment]
@mperyer1 The fix is released with the version 2.11.0 of SCM-Manager.

**Comment by mperyer1** [comment]
That's brilliant Thank you.

I've confirmed that everything is now working.
