### ISSUE TITLE
Import of existing Mercurial repository via new GUI feature failed

### ISSUE THREAD

**Issue by niks-** [scm-manager/scm-manager#1475]
## Issue description
I am trying to import existing Mercurial repository and it failed with "The repository could not be imported. It's likely that either the credentials (username/password) are wrong or missing. Please check your inputs." error message.
I double-checked all inputs and its correct.
Remote repo is accessable from the same browser on the same url with the same credentials 
I am able to create and use newly created Mercurial repo.

#### Describe how to reproduce the bug
1) Have a brand-new instance of SCM-Manager v2.11
2) Log in under scmadmin account
3) Configure Mercurial plugin
- HG Binary = C:\Program Files\Mercurial\hg.exe
- Python Binary = C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe
4) Go to "Add Repository" -> "Import existing repository"
5) Enter Remote repository url. E.g. http://my.oldreposerver.com/scm/hg/myrepo
6) Enter valid credentials of user who has read and write (even admin) access to existing repo
7) Click Import

Error message appears
"The repository could not be imported. It's likely that either the credentials (username/password) are wrong or missing. Please check your inputs."
![import_error](https://user-images.githubusercontent.com/8697655/101925958-3059cc00-3bdb-11eb-960d-13ad30ae8ae3.png)

#### Describe your SCM-Manager setup
SCM-Manager version - 2.11.1
scm-hg-plugin@2.11.1
scm-mail-plugin@2.4.0
scm-notify-plugin@2.0.1
scm-ci-plugin@2.1.0
scm-jira-plugin@2.3.0
scm-notify-plugin@2.0.1
scm-pushlog-plugin@2.1.1
scm-cas-plugin@2.2.1
scm-legacy-plugin@2.11.1
scm-ci-plugin@2.1.0
scm-statistic-plugin@2.0.0
scm-git-plugin@2.11.1
scm-activity-plugin@2.0.0
scm-ldap-plugin@2.0.1
scm-svn-plugin@2.11.1
scm-jira-plugin@2.3.0
scm-issuetracker-plugin@2.0.1
scm-jira-plugin@2.3.0

No any proxies

#### Which operating system, browser and versions do you use?
OS - Windows Sever 2019 x64
scm-server service is running under Local System account
Scm-Manager Home directory - C:\SCM-Manager-Data
Windows Firewall is disabled 
Chrome - v87.0.4280.88 (Official Build) (64-bit)
OpenJDK - v11

#### Log of the bug
scm-server.wrapper
```
2020-12-11 17:58:38,521 DEBUG - Starting WinSW in service mode
2020-12-11 17:58:38,631 INFO  - Starting C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\\bin\java -cp "C:\Program Files\SCM-Manager\conf";"C:\Program Files\SCM-Manager\lib\*" -DBASE_DIR="C:\Program Files\SCM-Manager" -Djava.awt.headless=true -Dlogback.configurationFile=logging.xml sonia.scm.server.ScmServerDaemon
2020-12-11 17:58:38,650 INFO  - Started process 4712
2020-12-11 17:58:38,660 DEBUG - Forwarding logs of the process System.Diagnostics.Process (java) to WinSW.SizeBasedRollingLogAppender
```

scm-manager
```
2020-12-11 17:58:42.223 [main] [          ] INFO  sonia.scm.lifecycle.classloading.ClassLoaderLifeCycle - create new simple ClassLoaderLifeCycle
2020-12-11 17:58:42.229 [main] [          ] INFO  sonia.scm.lifecycle.BootstrapContextFilter - register for restart events
2020-12-11 17:58:42.233 [main] [          ] INFO  sonia.scm.event.LegmanScmEventBus - create new event bus ScmEventBus-1
2020-12-11 17:58:42.294 [main] [          ] INFO  sonia.scm.event.ScmEventBus - use sonia.scm.event.LegmanScmEventBus as event bus implementation
2020-12-11 17:58:42.391 [main] [          ] INFO  sonia.scm.lifecycle.BootstrapContextListener - start scm-manager initialization
2020-12-11 17:58:42.955 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - collect plugins
2020-12-11 17:58:43.038 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-hg-plugin@2.11.1
+- scm-mail-plugin@2.4.0
   +- scm-notify-plugin@2.0.1
   +- scm-ci-plugin@2.1.0
   +- scm-jira-plugin@2.3.0
+- scm-notify-plugin@2.0.1
+- scm-pushlog-plugin@2.1.1
+- scm-cas-plugin@2.2.1
+- scm-legacy-plugin@2.11.1
+- scm-ci-plugin@2.1.0
+- scm-statistic-plugin@2.0.0
+- scm-git-plugin@2.11.1
+- scm-activity-plugin@2.0.0
+- scm-ldap-plugin@2.0.1
+- scm-svn-plugin@2.11.1
+- scm-jira-plugin@2.3.0
+- scm-issuetracker-plugin@2.0.1
   +- scm-jira-plugin@2.3.0

2020-12-11 17:58:43.880 [main] [          ] INFO  sonia.scm.update.repository.XmlRepositoryV1UpdateStep - no v1 repositories database file found
2020-12-11 17:58:44.105 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.mail.internal.MailModule
2020-12-11 17:58:44.106 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class com.cloudogu.scm.ci.ModuleBinder
2020-12-11 17:58:44.106 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.notify.NotifyConfigurationsModule
2020-12-11 17:58:44.106 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.activity.ActivityModule
2020-12-11 17:58:44.106 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.web.HgServletModule
2020-12-11 17:58:44.106 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.web.SvnServletModule
2020-12-11 17:58:44.106 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.web.GitServletModule
2020-12-11 17:58:44.106 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.jira.JiraModule
2020-12-11 17:58:44.107 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.notify.NotifyModule
2020-12-11 17:58:44.107 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.repository.hooks.HookModule
2020-12-11 17:58:44.107 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.legacy.LegacyModule
2020-12-11 17:58:44.107 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class com.cloudogu.scm.cas.config.ConfigurationModule
2020-12-11 17:58:44.107 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.auth.ldap.resource.LdapModule
2020-12-11 17:58:44.107 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.security.gpg.GPGModule
2020-12-11 17:58:44.129 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.filter.BaseUrlFilter to filter chain
2020-12-11 17:58:44.130 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.security.TokenExpiredFilter to filter chain
2020-12-11 17:58:44.130 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.web.filter.DefaultHttpProtocolServletAuthenticationFilter to filter chain
2020-12-11 17:58:44.130 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class com.cloudogu.scm.cas.browser.CasAuthenticationFilter to filter chain
2020-12-11 17:58:44.131 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.legacy.LegacyProtocolServletAuthenticationFilter to filter chain
2020-12-11 17:58:44.131 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.web.security.ApiAuthenticationFilter to filter chain
2020-12-11 17:58:44.131 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class com.cloudogu.scm.cas.browser.ForceCasLoginFilter to filter chain
2020-12-11 17:58:44.132 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.filter.MDCFilter to filter chain
2020-12-11 17:58:44.132 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.web.security.TokenRefreshFilter to filter chain
2020-12-11 17:58:44.132 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.lifecycle.RestartServlet to servlet chain
2020-12-11 17:58:44.132 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.web.protocol.HttpProtocolServlet to servlet chain
2020-12-11 17:58:44.133 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.web.i18n.I18nServlet to servlet chain
2020-12-11 17:58:44.134 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.WebResourceServlet to servlet chain
2020-12-11 17:58:44.140 [main] [          ] INFO  sonia.scm.util.ScmConfigurationUtil - load ScmConfiguration from file C:\SCM-Manager-Data\config\config.xml
2020-12-11 17:58:44.167 [main] [          ] INFO  sonia.scm.plugin.DefaultExtensionProcessor - start processing extensions
2020-12-11 17:58:44.190 [main] [          ] WARN  sonia.scm.plugin.ExtensionBinder - could not find extension for extension point interface sonia.scm.io.FileSystem
2020-12-11 17:58:44.207 [main] [          ] INFO  sonia.scm.plugin.DefaultExtensionProcessor - bound extensions in 40.51 ms
2020-12-11 17:58:44.305 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.web.security.AdministrationContextRealm
2020-12-11 17:58:44.306 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class com.cloudogu.scm.cas.rest.CasRestRealm
2020-12-11 17:58:44.306 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.security.BearerRealm
2020-12-11 17:58:44.306 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.security.ApiKeyRealm
2020-12-11 17:58:44.306 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class com.cloudogu.scm.cas.browser.CasTokenRealm
2020-12-11 17:58:44.307 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.auth.ldap.LdapRealm
2020-12-11 17:58:44.307 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.security.AnonymousRealm
2020-12-11 17:58:44.307 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.legacy.LegacyRealm
2020-12-11 17:58:44.307 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.security.DefaultRealm
2020-12-11 17:58:46.008 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.008 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.055 [main] [          ] WARN  sonia.scm.cache.GuavaCacheConfigurationReader - could not find manual configuration at C:\SCM-Manager-Data\ext\gcache.xml
2020-12-11 17:58:46.445 [main] [          ] INFO  sonia.scm.repository.DefaultRepositoryManager - added RepositoryHandler class sonia.scm.repository.SvnRepositoryHandler for type Type{name=svn, displayName=Subversion}
2020-12-11 17:58:46.445 [main] [          ] INFO  sonia.scm.repository.DefaultRepositoryManager - added RepositoryHandler class sonia.scm.repository.GitRepositoryHandler for type Type{name=git, displayName=Git}
2020-12-11 17:58:46.445 [main] [          ] INFO  sonia.scm.repository.DefaultRepositoryManager - added RepositoryHandler class sonia.scm.repository.HgRepositoryHandler for type Type{name=hg, displayName=Mercurial}
2020-12-11 17:58:46.445 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.445 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.461 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.461 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.user.AnonymousUserDeletionEventHandler
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.jira.JiraIssueTracker
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.GitRepositoryModifyListener
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.issuetracker.internal.IssuePostReceiveRepositoryHook
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.security.AuthorizationChangedEventProducer
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.DefaultRepositoryRoleManager
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.RemoveDeletedRepositoryRole
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.mail.internal.RepositoryImportHook
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.statistic.StatisticListener
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.config.ScmConfigurationChangedListener
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.activity.ActivityManager
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.pushlog.PushlogHook
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.LastModifiedUpdateListener
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.api.v2.resources.GitRepositoryConfigChangeClearRepositoryCacheListener
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.notify.NotifyRepositoryHook
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.user.DefaultUserManager
2020-12-11 17:58:46.539 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.issuetracker.internal.IssueRepositoryListener
2020-12-11 17:58:46.727 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.lifecycle.SetupContextListener$SetupAction in administration context
2020-12-11 17:58:46.727 [main] [          ] INFO  sonia.scm.web.security.AdministrationContextRealm - assign admin permissions to admin context user scmsystem
2020-12-11 17:58:46.727 [main] [          ] INFO  sonia.scm.activity.CacheWarmUpListener - start cache warm up
2020-12-11 17:58:46.727 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.activity.CacheWarmUpListener$CacheWarmUpAction in administration context
2020-12-11 17:58:46.805 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.repository.HealthCheckContextListener$HealthCheckStartupAction in administration context
2020-12-11 17:58:46.805 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.805 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
2020-12-11 17:58:46.883 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.statistic.StatisticBootstrapAction in administration context
2020-12-11 17:58:47.413 [qtp36333492-17] [          ] INFO  sonia.scm.lifecycle.modules.ResteasyAllInOneServletDispatcher - init resteasy
2020-12-11 17:59:22.673 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.api.v2.resources.RepositoryImportResource - start hg import for external url http://**********/scm/hg/qaa
2020-12-11 17:59:22.674 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.repository.DefaultRepositoryManager - create repository hg/qaa (AISIsVGuw1) of type hg
2020-12-11 17:59:22.693 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.io.DefaultFileSystem - create directory C:\SCM-Manager-Data\repositories\AISIsVGuw1
2020-12-11 17:59:22.925 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.security.DefaultAuthorizationCollector - invalidate cache, because of a received authorization event
2020-12-11 17:59:22.940 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.repository.api.PullCommandBuilder - pull changes from url http://**********/scm/hg/qaa
2020-12-11 17:59:23.526 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.repository.DefaultRepositoryManager - delete repository hg/qaa (AISIsVGuw1) of type hg
2020-12-11 17:59:23.533 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.io.DefaultFileSystem - destroy directory C:\SCM-Manager-Data\repositories\AISIsVGuw1
2020-12-11 17:59:23.536 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.security.DefaultAuthorizationCollector - invalidate cache, because of a received authorization event
2020-12-11 17:59:23.536 [ScmEventBus-1-3] [          ] INFO  sonia.scm.issuetracker.DataStoreBasedIssueTracker - remove handled marks from store AISIsVGuw1
2020-12-11 17:59:23.537 [qtp36333492-29] [C7SIsVGshY] INFO  sonia.scm.security.DefaultAuthorizationCollector - invalidate cache, because of a received authorization event
2020-12-11 17:59:23.546 [ScmEventBus-1-3] [          ] ERROR sonia.scm.issuetracker.internal.IssueRepositoryListener - could not remove handled marks
java.lang.IllegalStateException: location for repository AISIsVGuw1 does not exist
	at sonia.scm.repository.xml.PathBasedRepositoryLocationResolver$1.getLocation(PathBasedRepositoryLocationResolver.java:100)
	at sonia.scm.store.FileBasedStoreFactory.getStoreDirectory(FileBasedStoreFactory.java:89)
	at sonia.scm.store.FileBasedStoreFactory.getStoreLocation(FileBasedStoreFactory.java:73)
	at sonia.scm.store.FileBasedStoreFactory.getStoreLocation(FileBasedStoreFactory.java:66)
	at sonia.scm.store.JAXBDataStoreFactory.getStore(JAXBDataStoreFactory.java:57)
	at sonia.scm.store.TypedStoreParametersBuilder$OptionalRepositoryBuilder.build(TypedStoreParametersBuilder.java:139)
	at sonia.scm.issuetracker.DataStoreBasedIssueTracker.createDatastore(DataStoreBasedIssueTracker.java:69)
	at sonia.scm.issuetracker.DataStoreBasedIssueTracker.removeHandledMarks(DataStoreBasedIssueTracker.java:75)
	at sonia.scm.issuetracker.internal.IssueRepositoryListener.removeHandledMarks(IssueRepositoryListener.java:117)
	at sonia.scm.issuetracker.internal.IssueRepositoryListener.handleRepositoryEvent(IssueRepositoryListener.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.github.legman.EventHandler.handleEvent(EventHandler.java:101)
	at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
	at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:460)
	at com.github.legman.EventBus$4.run(EventBus.java:450)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-11 17:59:23.548 [ScmEventBus-1-1] [          ] ERROR com.github.legman.EventBus - ScmEventBus-1 - could not dispatch event: RepositoryEvent{eventType=DELETE, item=hg/qaa (AISIsVGuw1), oldItem=null} to handler SynchronizedEventHandler{null, public void sonia.scm.statistic.StatisticListener.onRepositoryEvent(sonia.scm.repository.RepositoryEvent), true}
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.github.legman.EventHandler.handleEvent(EventHandler.java:101)
	at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
	at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:460)
	at com.github.legman.EventBus$4.run(EventBus.java:450)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: location for repository AISIsVGuw1 does not exist
	at sonia.scm.repository.xml.PathBasedRepositoryLocationResolver$1.getLocation(PathBasedRepositoryLocationResolver.java:100)
	at sonia.scm.store.FileBasedStoreFactory.getStoreDirectory(FileBasedStoreFactory.java:89)
	at sonia.scm.store.FileBasedStoreFactory.getStoreLocation(FileBasedStoreFactory.java:73)
	at sonia.scm.store.FileBasedStoreFactory.getStoreLocation(FileBasedStoreFactory.java:66)
	at sonia.scm.store.JAXBDataStoreFactory.getStore(JAXBDataStoreFactory.java:57)
	at sonia.scm.store.TypedStoreParametersBuilder$OptionalRepositoryBuilder.build(TypedStoreParametersBuilder.java:139)
	at sonia.scm.statistic.StatisticManager.getStore(StatisticManager.java:69)
	at sonia.scm.statistic.StatisticManager.remove(StatisticManager.java:113)
	at sonia.scm.statistic.StatisticListener.onRepositoryEvent(StatisticListener.java:74)
	... 13 common frames omitted
2020-12-11 17:59:23.577 [ScmEventBus-1-2] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/emailnotification/import_failed_en.mustache
2020-12-11 17:59:23.578 [ScmEventBus-1-2] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at sonia/scm/mail/emailnotification/import_failed_en.mustache
2020-12-11 17:59:23.609 [ScmEventBus-1-2] [          ] WARN  sonia.scm.mail.spi.DefaultMailService - mail configuration is not valid
2020-12-11 18:00:00.800 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$480/0x0000000800841840 in administration context
2020-12-11 18:05:00.809 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$480/0x0000000800841840 in administration context
2020-12-11 18:05:50.266 [pool-7-thread-1] [          ] INFO  sonia.scm.admin.ReleaseFeedParser - Search for newer versions of SCM-Manager
2020-12-11 18:05:50.672 [pool-7-thread-1] [          ] INFO  sonia.scm.trace.LoggingExporter - received Release Feed span, which took 405ms:
 - url: https://scm-manager.org/download/rss.xml
 - method: GET
 - status: 200
2020-12-11 18:05:59.400 [qtp36333492-29] [5lSIsWw7ck] INFO  sonia.scm.plugin.PluginCenterLoader - fetch plugins from https://plugin-center-api.scm-manager.org/api/v1/plugins/2.11.1?os=Windows+Server+2019&arch=64
2020-12-11 18:05:59.640 [qtp36333492-29] [5lSIsWw7ck] INFO  sonia.scm.trace.LoggingExporter - received Plugin Center span, which took 239ms:
 - url: https://plugin-center-api.scm-manager.org/api/v1/plugins/2.11.1?os=Windows+Server+2019&arch=64
 - method: GET
 - status: 200
2020-12-11 18:10:00.814 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$480/0x0000000800841840 in administration context
2020-12-11 18:15:00.821 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$480/0x0000000800841840 in administration context
2020-12-11 18:20:00.828 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$480/0x0000000800841840 in administration context

```

**Comment by eheimbuch** [comment]
Hey @niks-,

thanks for the report. We will have a look into this and try to fix your issue asap.

**Comment by eheimbuch** [comment]
@niks- In the logs you provided i am missing some exception for the failed repository pull. It could look something like that: 
```
sonia.scm.repository.api.ImportFailedException: could not execute pull command
```

Could you please increase your Loglevel to TRACE and try to reproduce it again?

**Comment by niks-** [comment]
@eheimbuch Per your request I am attaching TRACE level logs.
[Trace.log](https://github.com/scm-manager/scm-manager/files/5695910/Trace.log)

It seems the root of the issue is that the repo I am trying to import has "largefiles" extension enabled.
I've tried to import other repo w/o this extension and it was successful.
However, still have a question where I should put/locate Mercuria.ini to let scm-manager know which mercurial config settings to use looking to the fact that scm-server service is running under Local System
I've tried and it didn't help
* C:\Mercurial\Mercurial.ini
* <install-dir>\Mercurial.ini
* C:\Windows\System32\config\systemprofile\AppData
* C:\ProgramData


'''
Caused by: com.aragost.javahg.commands.ExecutionException: remote error:

This repository uses the largefiles extension.

Please enable it in your Mercurial config file.
	at com.aragost.javahg.internals.AbstractCommand.handleReturnCode(AbstractCommand.java:387)
	at com.aragost.javahg.internals.OutputChannelInputStream.findNextOutputChannelBlock(OutputChannelInputStream.java:173)
	at com.aragost.javahg.internals.OutputChannelInputStream.read(OutputChannelInputStream.java:115)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:109)
	at com.aragost.javahg.internals.PullPushHelper.parseStream(PullPushHelper.java:92)
	at com.aragost.javahg.commands.PullCommand.run(PullCommand.java:62)
	at com.aragost.javahg.commands.PullCommand.execute(PullCommand.java:88)
	at sonia.scm.repository.spi.HgPullCommand.pull(HgPullCommand.java:70)
	... 122 common frames omitted
'''

**Comment by eheimbuch** [comment]
Hey @niks-,

we discussed this issue in our team and unfortunately we do not support repository import with the `largefiles` extension yet. But we are already working on to enhance the import and export features of SCM-Manager and will have a look at this matter.

**Comment by niks-** [comment]
@eheimbuch thanks for your update. 
The is still a workaround according to your documentation - to pull it manually.
You can close the issue then or move to the other required status.
Thanks to your product
