### ISSUE TITLE
HTTP OPTIONS returns 500 with long WARN in log file

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1685]
Our SCM Manager instance got recently upgraded to 2.19.0 and since then we are getting several long WARN messages in the log file with this message:

<pre>
WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected org.jboss.resteasy.spi.DefaultOptionsMethodException to status code 500
org.jboss.resteasy.spi.DefaultOptionsMethodException: RESTEASY003655: No resource method found for options, return OK with Allow header
</pre>

I've traced all these messages back to OPTION http requests. Some of them here (including the requests just before them for context):

<pre>
PUT /scm/api/v2/config HTTP/2.0 (204)
GET /scm/api/v2/config HTTP/2.0 (302)
OPTIONS /api/v2/config HTTP/2.0 (500)
------
GET /scm/api/v2/ HTTP/2.0 (302)
OPTIONS /api/v2/ HTTP/2.0 (500)
------
GET /scm/api/v2/me/notifications HTTP/2.0 (302)
GET /scm/api/v2/ HTTP/2.0 (302)
GET /scm/api/v2/me/ HTTP/2.0 (302)
GET /scm/api/v2/repositories/hg/REPONAME HTTP/2.0 (302)
OPTIONS /api/v2/me/notifications HTTP/2.0 (500)
OPTIONS /api/v2/repositories/hg/REPONAME HTTP/2.0 (500)
OPTIONS /api/v2/ HTTP/2.0 (500)
GET /scm/api/v2/me/notifications/subscribe?X-SCM-Client=WUI&X-SCM-Session-ID=*** HTTP/2.0 (302)
OPTIONS /api/v2/me/ HTTP/2.0 (500)
------
GET /scm/api/v2/me/notifications HTTP/2.0 (302)
GET /scm/api/v2/ HTTP/2.0 (302)
GET /scm/api/v2/me/ HTTP/2.0 (302)
GET /scm/api/v2/repositories/hg/REPONAME HTTP/2.0 (302)
OPTIONS /api/v2/me/notifications HTTP/2.0 (500)
OPTIONS /api/v2/ HTTP/2.0 (500)
OPTIONS /api/v2/me/ HTTP/2.0 (500)
OPTIONS /api/v2/repositories/hg/REPONAME HTTP/2.0 (500)
</pre>

There seem to be two slightly different stacktraces for these messages. The first one is by far more common:

<pre>
2021-06-07 12:09:12.330 [qtp1347137144-24853] [F5SZdsfd9ez1] WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected org.jboss.resteasy.spi.DefaultOptionsMe
thodException to status code 500
org.jboss.resteasy.spi.DefaultOptionsMethodException: RESTEASY003655: No resource method found for options, return OK with Allow header
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:442)
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:154)
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:74)
        at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:47)
        at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:481)
        at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:332)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:253)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...
</pre>

and

<pre>

2021-06-07 12:23:58.825 [qtp1347137144-24853] [8ZSZdwOFbfKz] WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected org.jboss.resteasy.spi.DefaultOptionsMe
thodException to status code 500
org.jboss.resteasy.spi.DefaultOptionsMethodException: RESTEASY003655: No resource method found for options, return OK with Allow header
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:442)
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:154)
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:74)
        at org.jboss.resteasy.core.LocatorRegistry.getResourceInvoker(LocatorRegistry.java:83)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:175)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...
</pre>

Our plugin tree:

<pre>
[main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-repository-avatar-plugin@1.0.1
+- scm-activity-plugin@2.0.0
+- scm-git-plugin@2.19.0
+- scm-legacy-plugin@2.19.0
+- scm-hg-plugin@2.19.0
+- scm-groupmanager-plugin@2.0.0
+- scm-ldap-plugin@2.3.0
+- scm-issuetracker-plugin@3.1.0
+- scm-mail-plugin@2.6.0
   +- scm-issuetracker-plugin@3.1.0
   +- scm-notify-plugin@2.0.1
+- scm-svn-plugin@2.19.0
+- scm-el-plugin@1.0.0
   +- scm-webhook-plugin@2.2.0
+- scm-webhook-plugin@2.2.0
+- scm-notify-plugin@2.0.1
</pre>

The server runs behind a nginx with reverse proxy.
All these requests were done with Firefox 89.0 for Windows.

I'm not sure how serious this warning is (I see my own IP in the logs but I don't recall any major problems when using the website), but since it includes a full stack trace every time, it might be worth to investigate - hence this issue.

Thanks in advance!

**Comment by sdorra** [comment]
The PR #1688 should fix the broken options request. However the web interface should not send any options request, are you sure that the requests are coming from a browser which is using the scm-manager webinterface? It looks like another webapp which is trying to use the scm-manager rest api, because the request are looking like preflight cors requests.

**Comment by fnajera-rac-de** [comment]
Thanks for the prompt response!

Yes, I am positive it was Firefox. We don't use or have any other webapp connected to SCM, and we have disabled the API access. All the user agents where Firefox (the exact same agent for each group). And those requests that I put above had all the same date/time (up to seconds, our log file doesn't include milliseconds).

But that is a good question indeed: I just went back to the log files and it seems, this only happened when we accessed the web through an alternative URL which **did not match the Base URL** in the settings. 

Unfortunately, I cannot replicate it now, but maybe that could explain why the browser acted as it did.

Here some of the nginx log entries with just the minimum redacted:

<pre>
[ip1] - - [07/Jun/2021:12:09:12 +0200] "PUT /scm/api/v2/config HTTP/2.0" 204 0 "https://[non-base-domain]/scm/admin/settings/general" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip1] - - [07/Jun/2021:12:09:12 +0200] "GET /scm/api/v2/config HTTP/2.0" 302 0 "https://[non-base-domain]/scm/admin/settings/general" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip1] - - [07/Jun/2021:12:09:12 +0200] "OPTIONS /api/v2/config HTTP/2.0" 500 113 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
--------
[ip2] - - [07/Jun/2021:12:23:58 +0200] "GET /scm/api/v2/me/notifications HTTP/2.0" 302 0 "https://[non-base-domain]/scm/repo/hg/[repo-name]/info" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "GET /scm/api/v2/ HTTP/2.0" 302 0 "https://[non-base-domain]/scm/repo/hg/[repo-name]/info" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "GET /scm/api/v2/me/ HTTP/2.0" 302 0 "https://[non-base-domain]/scm/repo/hg/[repo-name]/info" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "GET /scm/api/v2/repositories/hg/[repo-name] HTTP/2.0" 302 0 "https://[non-base-domain]/scm/repo/hg/[repo-name]/info" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "OPTIONS /api/v2/me/notifications HTTP/2.0" 500 115 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "OPTIONS /api/v2/repositories/hg/[repo-name] HTTP/2.0" 500 115 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "OPTIONS /api/v2/ HTTP/2.0" 500 115 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "GET /scm/api/v2/me/notifications/subscribe?X-SCM-Client=WUI&X-SCM-Session-ID=... HTTP/2.0" 302 0 "https://[non-base-domain]/scm/repo/hg/[repo-name]/info" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
[ip2] - - [07/Jun/2021:12:23:58 +0200] "OPTIONS /api/v2/me/ HTTP/2.0" 500 114 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
</pre>

Note the "-" as referrer in the Options entries.
