### ISSUE TITLE
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1690]
We have a huge mercurial repository, and a colleague tried to do a clone. 
He had to try 3-4 times. Each time the process worked for a while, and then it suddenly stopped with a message that the stream was interrupted.
Eventually he tried again and this time it worked.

On the SCM log files I can find this:

<pre>
2021-06-08 13:05:47.014 [qtp1347137144-13029] [8qSZjxCmPMOM] ERROR sonia.scm.web.HgCGIExceptionHandler - not able to handle mercurial request
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:234)
        at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:833)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:113)
        at sonia.scm.web.cgi.DefaultCGIExecutor.execute(DefaultCGIExecutor.java:399)
        at sonia.scm.web.cgi.DefaultCGIExecutor.execute(DefaultCGIExecutor.java:169)
        at sonia.scm.web.HgCGIServlet.process(HgCGIServlet.java:151)
        at sonia.scm.web.HgCGIServlet.handleRequest(HgCGIServlet.java:122)
        at sonia.scm.web.HgCGIServlet.service(HgCGIServlet.java:106)
        at sonia.scm.repository.spi.ScmProviderHttpServletDecorator.service(ScmProviderHttpServletDecorator.java:45)
        at sonia.scm.web.filter.PermissionFilter.service(PermissionFilter.java:116)
        at sonia.scm.web.HgPermissionFilter.service(HgPermissionFilter.java:64)
        at sonia.scm.repository.spi.InitializingHttpScmProtocolWrapper$ProtocolWrapper.serve(InitializingHttpScmProtocolWrapper.java:148)
        at sonia.scm.repository.spi.HttpScmProtocol.serve(HttpScmProtocol.java:59)
        at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:99)
        at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.noRedirect(RepositoryLegacyProtocolRedirectFilter.java:127)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.checkPathElements(RepositoryLegacyProtocolRedirectFilter.java:100)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.doFilter(RepositoryLegacyProtocolRedirectFilter.java:89)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter.doFilter(RepositoryLegacyProtocolRedirectFilter.java:71)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.MDCFilter.doFilter(MDCFilter.java:103)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.web.filter.AuthenticationFilter.processChain(AuthenticationFilter.java:266)
        at sonia.scm.web.filter.AuthenticationFilter.handleAuthentication(AuthenticationFilter.java:225)
        at sonia.scm.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:109)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.security.TokenExpiredFilter.doFilter(TokenExpiredFilter.java:66)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:109)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.metrics.HttpMetricsFilter.doFilter(HttpMetricsFilter.java:68)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
        at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 common frames omitted
</pre>

We are running behind an Nginx proxy, but I am not sure if that is involved here. The log file of nginx doesn't show anything special (apart from the size of the response which varies a lot, showing that indeed not all the data was transmitted)

<pre>
# failed
[ip] - [user] [08/Jun/2021:13:06:16 +0200] "GET /scm/repo/hg/[repo]/?cmd=getbundle HTTP/1.1" 200 31563869 "-" "mercurial/proto-1.0 (Mercurial 5.1)"
[ip] - [user] [08/Jun/2021:13:07:07 +0200] "GET /scm/repo/hg/[repo]/?cmd=getbundle HTTP/1.1" 200 49890368 "-" "mercurial/proto-1.0 (Mercurial 5.1)"
[ip] - [user] [08/Jun/2021:13:10:21 +0200] "GET /scm/repo/hg/[repo]/?cmd=getbundle HTTP/1.1" 200 150924630 "-" "mercurial/proto-1.0 (Mercurial 5.1)"
# correct
[ip] - [user] [08/Jun/2021:13:19:50 +0200] "GET /scm/repo/hg/[repo]/?cmd=getbundle HTTP/1.1" 200 463310729 "-" "mercurial/proto-1.0 (Mercurial 5.1)"
</pre>

Seeing how the response sizes are all-increasing, I wonder if the problem is that mercurial (or the repository storage) needs some time to fetch and prepare the response and that's when the timeout happens. Trying again, the reading goes a bit faster (some hw/sw cache involved?) but not quite, and there is another timeout, until it finally works.

Is there anything that could be improved here? Can the timeout (30s) be tuned?

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de 

If your hg repository is really that big, it is understandable that it can run into a timeout. Of course, this is still a bad state of affairs that we need to look at urgently. We will discuss this matter in our team and come back to you.

**Comment by eheimbuch** [comment]
Seems like this could already do the trick: https://github.com/scm-manager/scm-manager/blob/5f887d4fa8d11f471de981ec78f5e112d1863fcf/scm-webapp/src/main/java/sonia/scm/net/ahc/DefaultAdvancedHttpClient.java#L76

Not sure though.

**Comment by eheimbuch** [comment]
The first one is wrong. I got a better one: https://github.com/scm-manager/scm-manager/blob/5f887d4fa8d11f471de981ec78f5e112d1863fcf/scm-core/src/main/java/sonia/scm/io/ExtendedCommand.java#L112

I think we could make this timeout configurable on the global hg config.

**Comment by pfeuffer** [comment]
I created a hg repository with 10 files 40MB each. I cloned this repository over a 1 MBit/s connection directly from an SCM-Manager. This took round about 2 hours, but it did not interrupt.

Nginx has a setting named `proxy_request_buffering`. Can you try to set this to `off` and try again, @fnajera-rac-de ?

**Comment by fnajera-rac-de** [comment]
> Nginx has a setting named proxy_request_buffering. Can you try to set this to off and try again,

Sure, I can try that, but I doubt it will make a difference.

The error comes from SCM as it is written in its log file and it is prefixed with "not able to handle mercurial request".
This is not nginx closing a connection because of a timeout, it's a request which SCM initiates with Mercurial (probably via HgCGIServlet based on the stacktrace) which is timing out. 

One of our most problematic repositories has 3500+ revisions, 7800+ files and its .hg folder is 745 MB. 
Another has 3000 revisions, 23200+ files and the .hg folder is 758 MB.

I think that the problem is more the number of commits + the number of files affected per commit (which can be 3000+ files in our case) and the time that mercurial needs to gather all those changes and bundle them and pass them over in the stream.

**Comment by pfeuffer** [comment]
We just had a similar issue with SVN (you can find this on [StackOverflow](https://stackoverflow.com/questions/68015005/scm-manager-subversion-checkout-results-in-e175009-the-xml-response-contains-in). Here the jetty timeout was the cause. Can you try and set this to a higher value, eg. by adding

```xml
<Set name="idleTimeout">
    <Property name="jetty.timeout" default="300000" />
</Set>
```

to the `ServerConnector` in the `server-config.xml` and try once more? Thanks!

**Comment by pfeuffer** [comment]
Hi @fnajera-rac-de , did you have the opportunity to test an increased jetty timeout, yet? We would be interested in the results. Thank you :-)

**Comment by fnajera-rac-de** [comment]
@pfeuffer Sorry for the late response. I haven't seen any "Idle timeout" message in our logs lately, so it must have helped. Thank you!
