### ISSUE TITLE
Log file explosion by some mercurial URL GETs

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1702]
There is an exception written to the log file everytime you try to get the raw-file of a mercurial file which does not exist. 

To reproduce:

<pre>
curl -v --url https://[server]/scm/repo/hg/[repo]/raw-file/123456789012/non-existent-file.txt --user-agent Mercurial --user "[user:pass]"
...
< HTTP/1.1 404 Not Found
< Server: ...
< Date: Wed, 16 Jun 2021 11:07:45 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
<
* Connection #0 to host [server] left intact
</pre>

The client receives a 404 answer - which is correct - so from the point of view of the client all is OK.
But the log file grows with the ERROR messages shown here:

<pre>
2021-06-16 12:42:40.413 [qtp1347137144-25267] [2ISaUdp4h2jXx] ERROR sonia.scm.web.HgCGIExceptionHandler - not able to handle mercurial request
org.eclipse.jetty.io.EofException: Closed
        at org.eclipse.jetty.server.HttpOutput.checkWritable(HttpOutput.java:727)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:757)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:113)
        at sonia.scm.web.cgi.DefaultCGIExecutor.execute(DefaultCGIExecutor.java:399)
        at sonia.scm.web.cgi.DefaultCGIExecutor.execute(DefaultCGIExecutor.java:169)
        at sonia.scm.web.HgCGIServlet.process(HgCGIServlet.java:151)
        at sonia.scm.web.HgCGIServlet.handleRequest(HgCGIServlet.java:122)
        at sonia.scm.web.HgCGIServlet.service(HgCGIServlet.java:106)
        at sonia.scm.repository.spi.ScmProviderHttpServletDecorator.service(ScmProviderHttpServletDecorator.java:45)
        at sonia.scm.web.filter.PermissionFilter.service(PermissionFilter.java:116)
        at sonia.scm.web.HgPermissionFilter.service(HgPermissionFilter.java:64)
        at sonia.scm.repository.spi.InitializingHttpScmProtocolWrapper$ProtocolWrapper.serve(InitializingHttpScmProtocolWrapper.java:148)
        at sonia.scm.repository.spi.HttpScmProtocol.serve(HttpScmProtocol.java:59)
        at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:99)
        at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.noRedirect(RepositoryLegacyProtocolRedirectFilter.java:127)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.checkPathElements(RepositoryLegacyProtocolRedirectFilter.java:100)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.doFilter(RepositoryLegacyProtocolRedirectFilter.java:89)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter.doFilter(RepositoryLegacyProtocolRedirectFilter.java:71)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.MDCFilter.doFilter(MDCFilter.java:103)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.web.filter.AuthenticationFilter.processChain(AuthenticationFilter.java:266)
        at sonia.scm.web.filter.AuthenticationFilter.handleAuthentication(AuthenticationFilter.java:225)
        at sonia.scm.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:109)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.security.TokenExpiredFilter.doFilter(TokenExpiredFilter.java:66)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:109)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.metrics.HttpMetricsFilter.doFilter(HttpMetricsFilter.java:68)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-16 12:42:40.443 [cgi-pool-4410] [          ] ERROR sonia.scm.web.cgi.DefaultCGIExecutor - could not read errorstream
java.io.IOException: Stream closed
        at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:289)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
        at sonia.scm.util.IOUtil.copy(IOUtil.java:190)
        at sonia.scm.util.IOUtil.copy(IOUtil.java:172)
        at sonia.scm.web.cgi.DefaultCGIExecutor.processErrorStream(DefaultCGIExecutor.java:465)
        at sonia.scm.web.cgi.DefaultCGIExecutor.lambda$processErrorStreamAsync$0(DefaultCGIExecutor.java:489)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
</pre>

Note that if you use a revision number which does not exist, the error from 'cgi-pool-XXXX' seems not to happen, but the first one still does.

If you repeat this request a number of times, the log file grows really, really big and there are lots of ERROR messages which pollute it.

Just for comparison, this is what happens if you repeat the queries directly against a "hg serve" on the repository:

<pre>
curl -v --url http://[server]:8000/raw-file/123456789012/existent-file.txt 
...
< HTTP/1.1 200 Script output follows
< Server: BaseHTTP/0.3 Python/2.7.13
< Date: Wed, 16 Jun 2021 11:05:47 GMT
< ETag: W/"1623841243"
< Content-Type: application/binary
< Content-Disposition: inline; filename="dependencies.json"
< Content-Length: 108
<
filecontents
* Connection #0 to host [server] left intact

curl -v --url http://[server]:8000/raw-file/123456789012/non-existent-file.txt
...
< HTTP/1.1 404 Not Found
< Server: BaseHTTP/0.3 Python/2.7.13
< Date: Wed, 16 Jun 2021 11:04:19 GMT
< ETag: W/"1623841243"
< Content-Type: text/plain; charset=cp1252
< Transfer-Encoding: chunked
<

error: non-existent-file.txt@123456789012: not found in manifest
* Connection #0 to host [server] left intact

curl -v --url http://[server]:8000/raw-file/[non-existing-revision]/non-existent-file.txt 
< HTTP/1.1 404 Not Found
< Server: BaseHTTP/0.3 Python/2.7.13
< Date: Wed, 16 Jun 2021 11:06:16 GMT
< ETag: W/"1623841243"
< Content-Type: text/plain; charset=cp1252
< Transfer-Encoding: chunked
<

error: revision not found: [non-existing-revision]
* Connection #0 to host [server] left intact
</pre>

So again, the 404 answer of SCM is right, but I believe SCM should not be logging exceptions when these queries are executed.

<pre>
SCM version 2.19.1
2021-06-13 00:00:15.119 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-repository-avatar-plugin@1.0.1
+- scm-activity-plugin@2.0.0
+- scm-git-plugin@2.19.1
+- scm-legacy-plugin@2.19.1
+- scm-hg-plugin@2.19.1
+- scm-groupmanager-plugin@2.0.0
+- scm-ldap-plugin@2.3.0
+- scm-issuetracker-plugin@3.1.0
+- scm-mail-plugin@2.7.1
   +- scm-issuetracker-plugin@3.1.0
   +- scm-notify-plugin@2.0.2
+- scm-svn-plugin@2.19.1
+- scm-el-plugin@1.0.0
   +- scm-webhook-plugin@2.2.0
+- scm-webhook-plugin@2.2.0
+- scm-notify-plugin@2.0.2
</pre>

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de,

that is indeed quite annoying. We will try to handle this exception better.

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de 

We looked into this matter and it is pretty difficult to handle this exception. We don't believe we can fix this matter anytime soon. Instead we suggest that you use the SCM-Manager REST API, e. g. the content endpoint (/v2/repositories/{namespace}/{name}/content/{revision}/{path}) to get a file. 

To explore the SCM-Manager REST API including all plugins checkout the SCM-OpenAPI-Plugin.

Hope this helps.

**Comment by fnajera-rac-de** [comment]
Thanks for the update on this, @eheimbuch

Unfortunately, your work around still explodes the log file:

<pre>
2021-07-01 11:34:20.649 [qtp1347137144-29464] [7DSbu4VWr3Uyp] ERROR sonia.scm.repository.spi.HgCatCommand - could not execute cat command
com.aragost.javahg.commands.ExecutionException: [path-to-a-non-existing-file]: no such file in rev [revision]
        at com.aragost.javahg.internals.AbstractCommand.handleReturnCode(AbstractCommand.java:387)
        at com.aragost.javahg.internals.OutputChannelInputStream.findNextOutputChannelBlock(OutputChannelInputStream.java:173)
        at com.aragost.javahg.internals.OutputChannelInputStream.<init>(OutputChannelInputStream.java:74)
        at com.aragost.javahg.internals.Server.runCommand(Server.java:409)
        at com.aragost.javahg.internals.AbstractCommand.launchStream(AbstractCommand.java:180)
        at com.aragost.javahg.commands.CatCommand.execute(CatCommand.java:56)
        at sonia.scm.repository.spi.HgCatCommand.getCatResultStream(HgCatCommand.java:66)
        at sonia.scm.repository.api.CatCommandBuilder.getStream(CatCommandBuilder.java:118)
        at sonia.scm.api.v2.resources.ContentResource.getHead(ContentResource.java:215)
        at sonia.scm.api.v2.resources.ContentResource.createContentHeader(ContentResource.java:198)
        at sonia.scm.api.v2.resources.ContentResource.get(ContentResource.java:122)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:646)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:510)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:460)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:462)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:420)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.noRedirect(RepositoryLegacyProtocolRedirectFilter.java:127)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.checkPathElements(RepositoryLegacyProtocolRedirectFilter.java:100)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.doFilter(RepositoryLegacyProtocolRedirectFilter.java:89)
        at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter.doFilter(RepositoryLegacyProtocolRedirectFilter.java:71)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.web.security.TokenRefreshFilter.doFilter(TokenRefreshFilter.java:83)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.MDCFilter.doFilter(MDCFilter.java:103)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.web.filter.AuthenticationFilter.processChain(AuthenticationFilter.java:266)
        at sonia.scm.web.filter.AuthenticationFilter.handleAuthentication(AuthenticationFilter.java:225)
        at sonia.scm.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:109)
        at sonia.scm.web.security.ApiAuthenticationFilter.doFilter(ApiAuthenticationFilter.java:99)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.security.TokenExpiredFilter.doFilter(TokenExpiredFilter.java:66)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:109)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at sonia.scm.metrics.HttpMetricsFilter.doFilter(HttpMetricsFilter.java:68)
        at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:829)
</pre>

**Comment by eheimbuch** [comment]
I close this issue since we focus on support for the SCM-Manager API.
