### ISSUE TITLE
Could not send notification - java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1742]
I found this in our logs:

<pre>
2021-07-26 11:27:59.884 [ScmEventBus-1-1] [          ] ERROR sonia.scm.notify.DefaultNotifyHandler - could not send notification
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 102
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at sonia.scm.notify.AbstractContentBuilder.createSubject(AbstractContentBuilder.java:97)
        at sonia.scm.notify.DefaultNotifyHandler.sendMessage(DefaultNotifyHandler.java:123)
        at sonia.scm.notify.DefaultNotifyHandler.send(DefaultNotifyHandler.java:104)
        at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:106)
        at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:89)
        at sonia.scm.notify.NotifyRepositoryHook.onEvent(NotifyRepositoryHook.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.github.legman.InvocationContext.invoke(InvocationContext.java:108)
        at com.github.legman.InvocationContext.proceed(InvocationContext.java:101)
        at com.github.legman.micrometer.MicrometerInvocationInterceptor.invoke(MicrometerInvocationInterceptor.java:47)
        at com.github.legman.InvocationContext.proceed(InvocationContext.java:99)
        at com.github.legman.EventHandler.handleEvent(EventHandler.java:103)
        at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
        at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:452)
        at com.github.legman.EventBus.lambda$dispatch$1(EventBus.java:444)
        at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
        at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
</pre>

There's nothing special in the Email Notification configuration of the repository (mercurial):
- 9 emails
- [ ] Send to Repository contact
- [ ] Use Author as from Address
- [x] Email per Push
- Maximum Diff Lines: 300

SCM-Manager 2.21.0

<pre>
2021-07-25 00:00:13.471 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-repository-avatar-plugin@1.0.1
+- scm-activity-plugin@2.0.0
+- scm-git-plugin@2.21.0
+- scm-legacy-plugin@2.21.0
+- scm-hg-plugin@2.21.0
+- scm-groupmanager-plugin@2.0.0
+- scm-ldap-plugin@2.4.0
+- scm-issuetracker-plugin@3.1.0
+- scm-mail-plugin@2.7.1
   +- scm-issuetracker-plugin@3.1.0
   +- scm-notify-plugin@2.0.2
+- scm-svn-plugin@2.21.0
+- scm-el-plugin@1.0.0
   +- scm-webhook-plugin@2.2.0
+- scm-webhook-plugin@2.2.0
+- scm-notify-plugin@2.0.2
</pre>

**Comment by eheimbuch** [comment]
Thanks for the report. We will have a look.
