### ISSUE TITLE
Migration failed due to error with permissions, but after fixing error can't restart migration

### ISSUE THREAD

**Issue by mrPsycho** [scm-manager/scm-manager#1786]
## Issue description

Migration failed due to error with permissions, but after fixing error can't restart migration

#### Describe how to reproduce the bug

* upgrade from 1.60 to the latest
* start migration with COPY option
* catch error that it can't create temporary directory:  /var/lib/scm/repositories/B4PysbCiB1
* fix that error
* restart SCM-manager 
* get "[Guice/ErrorInjectingConstructor]: IllegalArgumentException: /var/lib/scm/repositories/B4PysbCiB1/metadata.xml (No such file or directory)"

#### Describe your SCM-Manager setup

SCM manager was upgraded from repository, but as root /var/lib/scm/repositories was mounted from other partition, it has wrong permissions.
New SCM required to have RW permissions to that, so i added, but after i got error. 

#### Which operating system, browser and versions do you use?

Ubuntu 20.04 LTS

#### Log of the bug

```
        com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: /var/lib/scm/repositories/B4PysbCiB1/metadata.xml (No such file or directory)
  at XmlRepositoryDAO.<init>(XmlRepositoryDAO.java:64)
  at XmlRepositoryDAO.class(XmlRepositoryDAO.java:50)
  at XmlRepositoryV1UpdateStep.<init>(XmlRepositoryV1UpdateStep.java:95)
      \_ for 2nd parameter
  while locating XmlRepositoryV1UpdateStep

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
XmlRepositoryDAO:          "sonia.scm.repository.xml.XmlRepositoryDAO"
XmlRepositoryV1UpdateStep: "sonia.scm.update.repository.XmlRepositoryV1UpdateStep"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
	at sonia.scm.update.MigrationWizardModuleProvider.wizardNecessary(MigrationWizardModuleProvider.java:44)
	at sonia.scm.lifecycle.BootstrapContextListener.startEitherMigrationOrApplication(BootstrapContextListener.java:130)
	at sonia.scm.lifecycle.BootstrapContextListener.createMigrationOrNormalModuleProvider(BootstrapContextListener.java:124)
	at sonia.scm.lifecycle.BootstrapContextListener.createStageTwoInjector(BootstrapContextListener.java:117)
	at sonia.scm.lifecycle.BootstrapContextListener.getInjector(BootstrapContextListener.java:93)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at sonia.scm.lifecycle.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:75)
	at sonia.scm.lifecycle.BootstrapContextFilter.initializeContext(BootstrapContextFilter.java:74)
	at sonia.scm.lifecycle.BootstrapContextFilter.init(BootstrapContextFilter.java:65)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:140)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at sonia.scm.server.ScmServer.init(ScmServer.java:130)
	at sonia.scm.server.ScmServer.run(ScmServer.java:91)
	at sonia.scm.server.ScmServerDaemon.main(ScmServerDaemon.java:53)
Caused by: java.lang.IllegalArgumentException: /var/lib/scm/repositories/B4PysbCiB1/metadata.xml (No such file or directory)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:166)
	at sonia.scm.repository.xml.MetadataStore.read(MetadataStore.java:58)
	at sonia.scm.repository.xml.XmlRepositoryDAO.lambda$init$0(XmlRepositoryDAO.java:78)
	at sonia.scm.repository.xml.PathBasedRepositoryLocationResolver$1.lambda$forAllLocations$0(PathBasedRepositoryLocationResolver.java:124)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at sonia.scm.repository.xml.PathBasedRepositoryLocationResolver$1.forAllLocations(PathBasedRepositoryLocationResolver.java:124)
	at sonia.scm.repository.xml.XmlRepositoryDAO.init(XmlRepositoryDAO.java:77)
	at sonia.scm.repository.xml.XmlRepositoryDAO.<init>(XmlRepositoryDAO.java:72)
	at sonia.scm.repository.xml.XmlRepositoryDAO$$FastClassByGuice$$25136623.GUICE$TRAMPOLINE(<generated>)
	at sonia.scm.repository.xml.XmlRepositoryDAO$$FastClassByGuice$$25136623.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
	... 36 more
```

**Comment by pfeuffer** [comment]
Thanks for the report! We will have a look whether we can make the migration process more robust at this point.
