### ISSUE TITLE
Cannot commit files in SVN with %20 in the path

### ISSUE THREAD

**Issue by ambassador86** [scm-manager/scm-manager#1817]
## Issue description

After upgrading to 2.20.0 we are unable to commit changes in some of our files containing %20 in their path.

#### Describe how to reproduce the bug

We have several SVN repositories where we store file with pathnames like this folder/part%20subpart/file.xml . Since our update from 1.60 to 2.20.0 we are unable to commit changes to these files oder add new files with this pattern.  On the client side subversion always complains about an outdated file and that the filesystem has no entry. On the server side there is an error in the logfile stating that the file could not be found E160013 followed by"Attempted to open non-existent child node 'part subpart'"

#### Describe your SCM-Manager setup

We are running SCM Manager on a windows server machine and behind an nginx proxy. The same error also occurs when bypassing the proxy. We use the standard set of plugins plus prometheus, ldap, jenkins and review.

#### Which operating system, browser and versions do you use?

The clients using the server are mostly windows with Subclipse, Subversive oder TortoiseSVN. 

#### Log of the bug

Client side log from tortoise

> Modified: C:\*retracted*\01%0020Service\ServicesDef\.info  
Error: Übertragen schlug fehl (Details folgen):  
Error: Datei  
Error:  »C:\*retracted*\01%0020Service\ServicesDef\.info«  
Error:  ist veraltet  
Error: Dateisystem hat keinen Eintrag  
Error: You have to update your working copy first.  

Server side log
>2021-09-29 15:12:17.219 [qtp489279267-13] [DoSkPCgD519] DEBUG svnkit.network - 
request.getPathInfo(): /!svn/ver/8050/trunk/*retracted*/01%0020Service/ServicesDef/.info
request.getPathTranslated(): D:\*retracted*\!svn\ver\8050\trunk\*retracted*\01%0020Service\ServicesDef\.info
..
request.getRequestURI(): /repo/svn/*retracted*/!svn/ver/8050/trunk/*retracted*/01%250020Service/ServicesDef/.info
request.getServerName(): ****
request.getServerPort(): 8080
request.getServletPath(): /repo/svn/***
request.getRequestURL(): https://host/repo/svn/*retracted*/!svn/ver/8050/trunk/*retracted*/01%250020Service/ServicesDef/.info
2021-09-29 15:12:17.235 [qtp489279267-13] [DoSkPCgD519] DEBUG svnkit.network - svn: E160013: File not found: transaction '8079-6n0', path '/trunk/*retracted*/01 20Service/ServicesDef/.info'
2021-09-29 15:12:17.235 [qtp489279267-13] [DoSkPCgD519] DEBUG svnkit.network - svn: E160013: Attempted to open non-existent child node '01 20Service'
2021-09-29 15:12:17.235 [qtp489279267-13] [DoSkPCgD519] DEBUG svnkit.network - Could not get created-rev of transaction node.
2021-09-29 15:12:17.235 [qtp489279267-13] [DoSkPCgD519] DEBUG svnkit.network - Could not CHECKOUT resource {0}.
2021-09-29 15:12:17.235 [qtp489279267-13] [DoSkPCgD519] DEBUG svnkit.network - Could not CHECKOUT resource /repo/svn/*retracted*/!svn/ver/8050/trunk/*retracted*/01%250020Service/ServicesDef/.info.
org.tmatesoft.svn.core.internal.server.dav.DAVException: Could not CHECKOUT resource /repo/svn/*retracted*/!svn/ver/8050/trunk/*retracted*/01%250020Service/ServicesDef/.info.
	at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVCheckOutHandler.execute(DAVCheckOutHandler.java:114)
	at org.tmatesoft.svn.core.internal.server.dav.DAVServlet.service(DAVServlet.java:136)
	at sonia.scm.web.SvnDAVServlet.service(SvnDAVServlet.java:107)
	at sonia.scm.web.SvnGZipFilter.service(SvnGZipFilter.java:62)
	at sonia.scm.repository.spi.ScmProviderHttpServletDecorator.service(ScmProviderHttpServletDecorator.java:45)

#### Further information like screenshots

I assume the is something wrong with escaping.

**Comment by eheimbuch** [comment]
Hey @ambassador86,

we will try to reproduce your error and get back to you. 

Could you also try to reproduce this error with a fresh SVN repository? Thanks.

**Comment by ambassador86** [comment]
Hello @eheimbuch ,
I was able to reproduce an error with a fresh repository, but the error messages are slighly different. On Client side I get an "invalid path syntax" error now.

And the server side looks like this:

> 2021-09-30 08:02:58.445 [qtp489279267-117] [6gSkTJ7lN1ye] DEBUG svnkit.network - 
request.getMethod(): MKCOL
request.getPathInfo(): /!svn/wrk/14b55aaa-4078-6d42-b5f8-1a36dd660cc9/*retracted*/01%0020Service
request.getPathTranslated(): D:\SCM-Manager\scm-server\work\scm-webapp\webapp\proof\errortest\!svn\wrk\14b55aaa-4078-6d42-b5f8-1a36dd660cc9\*retracted*\01%0020Service
request.getRequestURI(): /repo/proof/errortest/!svn/wrk/14b55aaa-4078-6d42-b5f8-1a36dd660cc9/*retracted*/01%250020Service
request.getServletPath(): /repo/proof/errortest
request.getRequestURL(): https://host/repo/proof/errortest/!svn/wrk/14b55aaa-4078-6d42-b5f8-1a36dd660cc9/*retracted*/01%250020Service
2021-09-30 08:02:58.445 [qtp489279267-117] [6gSkTJ7lN1ye] DEBUG svnkit.network - svn: E160005: Invalid control character '0x00' in path '/*retracted*/01 20Service'
2021-09-30 08:02:58.445 [qtp489279267-117] [6gSkTJ7lN1ye] DEBUG svnkit.network - Could not create the collection.
2021-09-30 08:02:58.445 [qtp489279267-117] [6gSkTJ7lN1ye] DEBUG svnkit.network - Could not create the collection.
org.tmatesoft.svn.core.internal.server.dav.DAVException: Could not create the collection.
	at org.tmatesoft.svn.core.internal.server.dav.DAVException.convertError(DAVException.java:145)
	at org.tmatesoft.svn.core.internal.server.dav.handlers.ServletDAVHandler.createdCollection(ServletDAVHandler.java:1464)
	at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVMakeCollectionHandler.execute(DAVMakeCollectionHandler.java:58)
	at org.tmatesoft.svn.core.internal.server.dav.DAVServlet.service(DAVServlet.java:136)
	at sonia.scm.web.SvnDAVServlet.service(SvnDAVServlet.java:107)
	at sonia.scm.web.SvnGZipFilter.service(SvnGZipFilter.java:62)
	at sonia.scm.repository.spi.ScmProviderHttpServletDecorator.service(ScmProviderHttpServletDecorator.java:45)
	at sonia.scm.web.filter.PermissionFilter.service(PermissionFilter.java:116)
	at sonia.scm.repository.spi.InitializingHttpScmProtocolWrapper$ProtocolWrapper.serve(InitializingHttpScmProtocolWrapper.java:148)
	at sonia.scm.repository.spi.HttpScmProtocol.serve(HttpScmProtocol.java:59)
	at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:99)
	at sonia.scm.web.protocol.HttpProtocolServlet.service(HttpProtocolServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2021-09-30 08:02:58.445 [qtp489279267-117] [6gSkTJ7lN1ye] DEBUG svnkit.network - <?xml version="1.0" encoding="UTF-8"?>
<D:error xmlns:D="DAV:" xmlns:m="http://apache.org/dav/xmlns" xmlns:C="svn:">
<C:error/><m:human-readable errcode="160005">
svn: E160005: Invalid control character '0x00' in path '/*retracted*/01 20Service'
</m:human-readable>
</D:error>

**Comment by sdorra** [comment]
Ok, i can confirm it is a bug. But the good news is that I could already find the error.
