### ISSUE TITLE
[GIT] Merge Pull Request error Code CmR8GCJb31

### ISSUE THREAD

**Issue by host-guru** [scm-manager/scm-manager#1829]
Since Update 2.24.0 we have an issue with GIT Repositorys Merging Pull Requests.

here is a example of the log file:
2021-10-18 12:26:06.023 [qtp971848845-120] [7HSmC72RK5w] WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected java.lang.NullPointerException to status code 500
java.lang.NullPointerException: null
        at sonia.scm.user.EMail.getMailOrFallback(EMail.java:62)
        at sonia.scm.repository.api.MergeCommandBuilder.setAuthor(MergeCommandBuilder.java:159)
        at com.cloudogu.scm.review.pullrequest.service.MergeService.prepareMergeCommand(MergeService.java:346)
        at com.cloudogu.scm.review.pullrequest.service.MergeService.lambda$merge$0(MergeService.java:106)
        at com.cloudogu.scm.review.InternalMergeSwitch.runInternalMerge(InternalMergeSwitch.java:37)
        at com.cloudogu.scm.review.pullrequest.service.MergeService.merge(MergeService.java:102)
        at com.cloudogu.scm.review.pullrequest.api.MergeResource.merge(MergeResource.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:646)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:510)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:460)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)

![image](https://user-images.githubusercontent.com/70758526/137746643-23f7098b-db78-45a7-b3a5-e1e8172489bb.png)

Please help!

**Comment by eheimbuch** [comment]
Hey @host-guru,

we are really sorry you got this error. We already fixed the issue [here](https://github.com/scm-manager/scm-review-plugin/pull/155). The next release which includes the fix will be out by tomorrow.
