### ISSUE TITLE
Error getting branch name (line read: 'invalid branch cache (served ): tip differs')

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1863]
We have a new error in our log file:

<pre>
2021-11-18 08:46:48.476 [HgHookWorker-4] [BUSp6F15XGMy] ERROR com.aragost.javahg.commands.BranchesCommand - Error getting branch name (line read: 'invalid branch cache (served
): tip differs')
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: 'invalid branch cache (served): tip differs' is not a node ID!!
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
        at com.aragost.javahg.Repository.basicChangeset(Repository.java:175)
        at com.aragost.javahg.Repository.changeset(Repository.java:162)
        at com.aragost.javahg.Branch.fromLine(Branch.java:59)
        at com.aragost.javahg.commands.BranchesCommand.execute(BranchesCommand.java:60)
        at sonia.scm.repository.spi.HgBranchesCommand.getBranches(HgBranchesCommand.java:63)
        at sonia.scm.repository.spi.BranchesCommand.getBranchesWithStaleFlags(BranchesCommand.java:42)
        at sonia.scm.repository.api.BranchesCommandBuilder.getBranchesFromCommand(BranchesCommandBuilder.java:168)
        at sonia.scm.repository.api.BranchesCommandBuilder.getBranches(BranchesCommandBuilder.java:107)
        at sonia.scm.repository.DefaultBranchDeleteProtection.getBranches(DefaultBranchDeleteProtection.java:79)
        at sonia.scm.repository.DefaultBranchDeleteProtection.checkDeletedBranches(DefaultBranchDeleteProtection.java:66)
        at sonia.scm.repository.DefaultBranchDeleteProtection.protectDefaultBranch(DefaultBranchDeleteProtection.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.github.legman.InvocationContext.invoke(InvocationContext.java:108)
        at com.github.legman.InvocationContext.proceed(InvocationContext.java:101)
        at com.github.legman.micrometer.MicrometerInvocationInterceptor.invoke(MicrometerInvocationInterceptor.java:47)
        at com.github.legman.InvocationContext.proceed(InvocationContext.java:99)
        at com.github.legman.EventHandler.handleEvent(EventHandler.java:103)
        at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
        at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:452)
        at com.github.legman.EventBus.dispatch(EventBus.java:446)
        at com.github.legman.EventBus.dispatchSynchronousQueuedEvents(EventBus.java:421)
        at com.github.legman.EventBus.post(EventBus.java:333)
        at sonia.scm.event.LegmanScmEventBus.post(LegmanScmEventBus.java:92)
        at sonia.scm.repository.AbstractRepositoryManager.fireHookEvent(AbstractRepositoryManager.java:57)
        at sonia.scm.repository.spi.HookEventFacade$HookEventHandler.fireHookEvent(HookEventFacade.java:137)
        at sonia.scm.repository.hooks.DefaultHookHandler.fireHook(DefaultHookHandler.java:119)
        at sonia.scm.repository.hooks.DefaultHookHandler.handleHookRequest(DefaultHookHandler.java:105)
        at sonia.scm.repository.hooks.DefaultHookHandler.handleHookRequest(DefaultHookHandler.java:90)
        at sonia.scm.repository.hooks.DefaultHookHandler.run(DefaultHookHandler.java:77)
        at sonia.scm.repository.hooks.HookServer.lambda$associateSecurityManager$1(HookServer.java:103)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: 'invalid branch cache (served): tip differs' is not a node ID!!
        at com.aragost.javahg.Changeset.<init>(Changeset.java:117)
        at com.aragost.javahg.Repository$1.load(Repository.java:348)
        at com.aragost.javahg.Repository$1.load(Repository.java:345)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 41 common frames omitted
</pre>

Is this something we should be worried about?

**Comment by fnajera-rac-de** [comment]
I've done a bit of googling, and found out this:

https://secure.phabricator.com/D21677

<pre>
    //
    // When Mercurial repositories are hosted on external systems with
    // multi-user environments it's possible that the branch cache is computed
    // on a revision which does not end up being published. When this happens it
    // will recompute the cache but also print out "invalid branch cache".
    //
</pre>

This would suggest that the line "invalid branch cache" that mercurial outputs is harmless, and SCM should just skip it and parse the next line if it happens.

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de,

thanks for the report and you already found a possible solution. We will look into this issue.

Could you please describe how to reproduce this error? Or even provide a example repo?

Thanks, Eduard

**Comment by fnajera-rac-de** [comment]
Not very orthodox but effective: 

* Edit the file .hg/cache/branch2-served and corrupt it by changing the first character to another hex value.

I don't know exactly how to trigger the stacktrace of the error log, but if you can do that, you should get the "invalid branch cache" message - and then mercurial will self-heal, so if you want to replicate this, you need to "corrupt" the file again after each operation.

Note that there are other similar texts that mercurial might show. Try deleting all the contents of the file, for example.

**Comment by eheimbuch** [comment]
Thanks, we will try to reproduce this and get back to you.

**Comment by eheimbuch** [comment]
Okay, i have looked into it and got some more questions.

Is the way we reproduced it also the actual error you stumbled upon? I mean is your repository also self healing after this exception happened? And how did you find out about this on the first hand? Are you manipulating your changesets or somewhat like that?

This error is most likely not inside SCM-Manager but in javahg (the mercurial library we use). It makes sense to me that this error is thrown if the cache is indeed invalid. Now we have to decide whether we try to fix this by some workaround or leave it be because the self healing is enough. What is you opinion about this?

**Comment by pfeuffer** [comment]
We still have not managed to reproduce your error (we do not get the `branch2-served` file). Can you give us a way to reproduce this starting with an empty repository or create a repository with this error that you can send to us?

**Comment by Amenel** [comment]
I'm replying because I have been the maintainer of JavaHg for some years now and I came across this conversation in a web search. I face this corruption of the command line output daily when I'm working on JavaHg or MercurialEclipse. I remember having tweaked the library a few years back to specifically work around such extraneous messages output by Mercurial.

@pfeuffer You also need to set Hg to debug mode before you see this message in a console: in your user .hgrc file, you can set `debug=True` or you can use `ui.debug=True` when executing a command on the command line. Moreover, an easy way to encounter this "invalid branch cache (immutable): tip differs" error message is to enable the evolve extension (on a specific repository, i.e. in the hgrc file of the repo; DO NOT enable it in your user .hgrc file). No need to push to a remote server, as evolve is enough to cause this message after one commit.

@fnajera-rac-de I see from the stacktrace that you have `com.aragost.javahg`, which means that you are not up-to-date with the latest JavaHg version. Since I've worked around these messages years back, the version of JavaHg you are using is probably very old. All versions are now published on Maven Central repositories, since December 2020. You might want to update your Maven coordinates for JavaHg to org.javahg:javahg:1.0.0 if you're directly pulling it in as a dependency. This is a comment where I said I had fixed the issue: https://foss.heptapod.net/mercurial/mercurialeclipse/-/issues/531#note_84845

**Comment by Amenel** [comment]
@pfeuffer My bad for mixing up responsibilities here. I'm taking note of the fact that the errors also occurs with version 1.0.0, which is the most recent version. I'll be releasing a new version this month. Then, I'll make a special round of commits to work around debug messages: it's on me to fix JavaHg.

NOTE: if the version is indeed 1.0.0, the base package listed in the OP stacktrace would be `org.javahg`, not `com.aragost.javahg`. You should check with dependency:list which version is actually bundled with the end product. Or I blundered somewhere.

I generally avoid using evolve simply because it causes those error messages. However, because of my work on Mercurial-related OSS projects, I need to have the debug mode enabled.

As to the remote server questions, here are some elements of comprehension. JavaHg is currently hosted on Heptapod, which supports and recommends a feature called "topics" (it so happens that the author of evolve is involved in Heptapod). On my workstation, evolve is enabled on javahg and mercurialeclipse repositories only, because the remote server supports topics and I am using topics on these OSS projects. As far as I understood:

- local copies need evolve to be able to exchange relevant data with remote servers, 
- neither the server nor the client _need_ evolve, but if enabled on both ends, something will be exchanged, 
- if it's not enabled on either end, it should not cause any problems,
- one local copy may have evolve enabled when no other copies including the remote server has enabled the extension.

Check the reference starting here, to confirm or refute items from the above list: https://pypi.org/project/hg-evolve/

I don't think that evolve is the sole cause for these messages. I think any extension that touches the history or commit log but is not fully taken into account in all of Hg code will cause such messages.

**Comment by Amenel** [comment]
I've had a thought: if you can find and remove what enables the debug mode on the remote server, it will prevent all exceptions due to extraneous output. Unless debug mode is necessary for something else. I suppose that either a file (hgrc or .hgrc) or a command line option does the enabling.

**Comment by pfeuffer** [comment]
Ah, only now I get it: There is no error I can see by enabling debug, but the hg debug mode creates the error? Have I got it right?

I don't think that we set the debug mode explicitly somewhere in SCM-Manager. So maybe this was caused by a global setting somewhere.
