### ISSUE TITLE
2.35.0 - Broken notifications - could not send notification, could not append diff

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#2063]
SCM Manager 2.35.0 has broken our notifications. Here are some log extracts:

<pre>
2022-06-08 08:32:03.510 [ScmEventBus-1-3] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/notify/template/content_en.mustache
2022-06-08 08:32:03.510 [ScmEventBus-1-3] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/notify/template/content_en.mustache
2022-06-08 08:32:03.527 [ScmEventBus-1-3] [          ] INFO  sonia.scm.repository.api.ModificationsCommandBuilder - Get modifications for ModificationsCommandRequest(revision=81f98d2fde768863c37a8db0da4515
2022-06-08 08:32:03.542 [ScmEventBus-1-3] [          ] WARN  org.javahg.internals.Server - Trying to stop already stopped server
2022-06-08 08:32:03.546 [ScmEventBus-1-3] [          ] ERROR sonia.scm.notify.DefaultNotifyHandler - could not send notification
sonia.scm.mail.spi.content.MailContentException: failed to render template: sonia.scm.template.MustacheTemplate@297d7014
       at sonia.scm.mail.spi.content.AbstractTemplateContentRenderer.renderTemplate(AbstractTemplateContentRenderer.java:52)
       at sonia.scm.mail.spi.content.AbstractTemplateContentRenderer.renderAsString(AbstractTemplateContentRenderer.java:44)
       at sonia.scm.mail.spi.content.AbstractMarkdownContentRenderer.render(AbstractMarkdownContentRenderer.java:40)
       at sonia.scm.mail.spi.content.MailContentRenderer.createMailContent(MailContentRenderer.java:39)
       at sonia.scm.mail.spi.DefaultMailService$MailBuilderImpl.createMailContent(DefaultMailService.java:413)
       at sonia.scm.mail.spi.DefaultMailService$MailBuilderImpl.createMail(DefaultMailService.java:403)
       at sonia.scm.mail.spi.DefaultMailService$MailBuilderImpl.send(DefaultMailService.java:392)
       at sonia.scm.notify.DefaultNotifyHandler.sendMessage(DefaultNotifyHandler.java:126)
       at sonia.scm.notify.DefaultNotifyHandler.send(DefaultNotifyHandler.java:104)
       at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:106)
       at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:89)
       at sonia.scm.notify.NotifyRepositoryHook.onEvent(NotifyRepositoryHook.java:76)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at com.github.legman.InvocationContext.invoke(InvocationContext.java:108)
       at com.github.legman.InvocationContext.proceed(InvocationContext.java:101)
       at com.github.legman.micrometer.MicrometerInvocationInterceptor.invoke(MicrometerInvocationInterceptor.java:47)
       at com.github.legman.InvocationContext.proceed(InvocationContext.java:99)
       at com.github.legman.EventHandler.handleEvent(EventHandler.java:103)
       at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
       at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:452)
       at com.github.legman.EventBus.lambda$dispatch$1(EventBus.java:444)
       at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
       at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: sonia.scm.template.TemplateRenderException: could not render template /sonia/scm/notify/template/content.mustache
       at sonia.scm.template.MustacheTemplate.execute(MustacheTemplate.java:65)
       at sonia.scm.mail.spi.content.AbstractTemplateContentRenderer.renderTemplate(AbstractTemplateContentRenderer.java:49)
       ... 28 common frames omitted
Caused by: com.github.mustachejava.MustacheException: Error invoking method sonia.scm.notify.ChangesetTemplateWrapper.getModifications() on sonia.scm.notify.ChangesetTemplateWrapper@826091692 @[/sonia/scm/
       at com.github.mustachejava.reflect.ReflectionWrapper.call(ReflectionWrapper.java:68)
       at com.github.mustachejava.reflect.ReflectionObjectHandler.find(ReflectionObjectHandler.java:94)
       at com.github.mustachejava.reflect.GuardedBinding.getWrapper(GuardedBinding.java:103)
       at com.github.mustachejava.reflect.GuardedBinding.createAndGet(GuardedBinding.java:89)
       at com.github.mustachejava.reflect.GuardedBinding.get(GuardedBinding.java:84)
       at com.github.mustachejava.codes.DefaultCode.get(DefaultCode.java:145)
       at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:41)
       at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34)
       at com.github.mustachejava.codes.DefaultCode.run(DefaultCode.java:213)
       at com.github.mustachejava.codes.IterableCode.next(IterableCode.java:143)
       at com.github.mustachejava.reflect.BaseObjectHandler.iterate(BaseObjectHandler.java:85)
       at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:138)
       at com.github.mustachejava.codes.IterableCode.handle(IterableCode.java:54)
       at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:42)
       at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34)
       at com.github.mustachejava.codes.DefaultCode.run(DefaultCode.java:213)
       at com.github.mustachejava.codes.IterableCode.next(IterableCode.java:143)
       at com.github.mustachejava.reflect.BaseObjectHandler.iterate(BaseObjectHandler.java:85)
       at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:138)
       at com.github.mustachejava.codes.IterableCode.handle(IterableCode.java:54)
       at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:42)
       at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34)
       at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:162)
       at com.github.mustachejava.codes.DefaultMustache.execute(DefaultMustache.java:57)
       at com.github.mustachejava.Mustache.execute(Mustache.java:38)
       at sonia.scm.template.MustacheTemplate.execute(MustacheTemplate.java:59)
       ... 29 common frames omitted
Caused by: java.lang.NullPointerException: null
       at org.javahg.internals.Server.sendCommand(Server.java:444)
       at org.javahg.internals.Server.runCommand(Server.java:409)
       at org.javahg.internals.AbstractCommand.launchStream(AbstractCommand.java:181)
       at sonia.scm.repository.spi.javahg.HgLogChangesetCommand.getHgInputStream(HgLogChangesetCommand.java:83)
       at sonia.scm.repository.spi.javahg.HgLogChangesetCommand.extractModifications(HgLogChangesetCommand.java:69)
       at sonia.scm.repository.spi.HgModificationsCommand.getModifications(HgModificationsCommand.java:45)
       at sonia.scm.repository.spi.ModificationsCommand.getModifications(ModificationsCommand.java:71)
       at sonia.scm.repository.api.ModificationsCommandBuilder.getModifications(ModificationsCommandBuilder.java:128)
       at sonia.scm.notify.ChangesetTemplateWrapper.getModifications(ChangesetTemplateWrapper.java:202)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at com.github.mustachejava.reflect.ReflectionWrapper.call(ReflectionWrapper.java:62)
       ... 54 common frames omitted
</pre>

<pre>
2022-06-08 08:33:56.110 [ScmEventBus-1-3] [          ] WARN  org.javahg.internals.Server - Trying to stop already stopped server
2022-06-08 08:33:56.110 [ScmEventBus-1-3] [          ] ERROR sonia.scm.notify.ChangesetTemplateWrapperHelper - could not append diff
java.lang.NullPointerException: null
       at org.javahg.internals.Server.sendCommand(Server.java:444)
       at org.javahg.internals.Server.runCommand(Server.java:409)
       at org.javahg.internals.AbstractCommand.launchStream(AbstractCommand.java:181)
       at sonia.scm.repository.spi.javahg.HgDiffInternalCommand.stream(HgDiffInternalCommand.java:127)
       at sonia.scm.repository.spi.HgDiffCommand.streamDiff(HgDiffCommand.java:90)
       at sonia.scm.repository.spi.HgDiffCommand.diff(HgDiffCommand.java:64)
       at sonia.scm.repository.spi.HgDiffCommand.lambda$getDiffResult$0(HgDiffCommand.java:54)
       at sonia.scm.repository.api.DiffCommandBuilder.getContent(DiffCommandBuilder.java:114)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.createDiff(ChangesetTemplateWrapperHelper.java:182)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.wrap(ChangesetTemplateWrapperHelper.java:251)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.wrap(ChangesetTemplateWrapperHelper.java:233)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.wrapAndSortByBranch(ChangesetTemplateWrapperHelper.java:125)
       at sonia.scm.notify.DefaultContentBuilder.createModel(DefaultContentBuilder.java:60)
       at sonia.scm.notify.DefaultNotifyHandler.sendMessage(DefaultNotifyHandler.java:125)
       at sonia.scm.notify.DefaultNotifyHandler.send(DefaultNotifyHandler.java:104)
       at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:106)
       at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:89)
       at sonia.scm.notify.NotifyRepositoryHook.onEvent(NotifyRepositoryHook.java:76)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at com.github.legman.InvocationContext.invoke(InvocationContext.java:108)
       at com.github.legman.InvocationContext.proceed(InvocationContext.java:101)
       at com.github.legman.micrometer.MicrometerInvocationInterceptor.invoke(MicrometerInvocationInterceptor.java:47)
       at com.github.legman.InvocationContext.proceed(InvocationContext.java:99)
       at com.github.legman.EventHandler.handleEvent(EventHandler.java:103)
       at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
       at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:452)
       at com.github.legman.EventBus.lambda$dispatch$1(EventBus.java:444)
       at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
       at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at java.base/java.lang.Thread.run(Thread.java:829)
</pre>

<pre>
2022-06-08 08:47:51.513 [ScmEventBus-1-2] [          ] ERROR sonia.scm.notify.ChangesetTemplateWrapperHelper - could not append diff
java.lang.IllegalStateException: Server pool is stopped
       at org.javahg.internals.ServerPool.take(ServerPool.java:149)
       at org.javahg.internals.AbstractCommand.launchStream(AbstractCommand.java:167)
       at sonia.scm.repository.spi.javahg.HgDiffInternalCommand.stream(HgDiffInternalCommand.java:127)
       at sonia.scm.repository.spi.HgDiffCommand.streamDiff(HgDiffCommand.java:90)
       at sonia.scm.repository.spi.HgDiffCommand.diff(HgDiffCommand.java:64)
       at sonia.scm.repository.spi.HgDiffCommand.lambda$getDiffResult$0(HgDiffCommand.java:54)
       at sonia.scm.repository.api.DiffCommandBuilder.getContent(DiffCommandBuilder.java:114)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.createDiff(ChangesetTemplateWrapperHelper.java:182)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.wrap(ChangesetTemplateWrapperHelper.java:251)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.wrap(ChangesetTemplateWrapperHelper.java:233)
       at sonia.scm.notify.ChangesetTemplateWrapperHelper.wrapAndSortByBranch(ChangesetTemplateWrapperHelper.java:125)
       at sonia.scm.notify.DefaultContentBuilder.createModel(DefaultContentBuilder.java:60)
       at sonia.scm.notify.DefaultNotifyHandler.sendMessage(DefaultNotifyHandler.java:125)
       at sonia.scm.notify.DefaultNotifyHandler.send(DefaultNotifyHandler.java:104)
       at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:106)
       at sonia.scm.notify.NotifyRepositoryHook.handleEvent(NotifyRepositoryHook.java:89)
       at sonia.scm.notify.NotifyRepositoryHook.onEvent(NotifyRepositoryHook.java:76)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at com.github.legman.InvocationContext.invoke(InvocationContext.java:108)
       at com.github.legman.InvocationContext.proceed(InvocationContext.java:101)
       at com.github.legman.micrometer.MicrometerInvocationInterceptor.invoke(MicrometerInvocationInterceptor.java:47)
       at com.github.legman.InvocationContext.proceed(InvocationContext.java:99)
       at com.github.legman.EventHandler.handleEvent(EventHandler.java:103)
       at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
       at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:452)
       at com.github.legman.EventBus.lambda$dispatch$1(EventBus.java:444)
       at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
       at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at java.base/java.lang.Thread.run(Thread.java:829)
</pre>

Our plugins:

<pre>
2022-06-07 18:25:57.412 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - collect plugins            
2022-06-07 18:25:57.573 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:       
+- scm-mail-plugin@2.7.2                                                                                        
   +- scm-issuetracker-plugin@3.2.1                                                                             
   +- scm-notify-plugin@2.0.3                                                                                   
+- scm-issuetracker-plugin@3.2.1                                                                                
+- scm-webhook-plugin@2.2.1                                                                                     
+- scm-repository-avatar-plugin@1.2.0                                                                           
+- scm-git-plugin@2.35.0                                                                                        
+- scm-legacy-plugin@2.35.0                                                                                     
+- scm-hg-plugin@2.35.0                                                                                         
+- scm-groupmanager-plugin@2.0.0                                                                                
+- scm-ldap-plugin@2.4.0                                                                                        
+- scm-landingpage-plugin@1.10.0                                                                                
+- scm-svn-plugin@2.35.0                                                                                        
+- scm-el-plugin@1.0.0                                                                                          
   +- scm-webhook-plugin@2.2.1                                                                                  
+- scm-notify-plugin@2.0.3                                                                                      
</pre>

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de 

we managed to fix this error. Please update your notify plugin to version 2.0.4.
