### ISSUE TITLE
Unable to migrate from 1.60 to 2.39.0: Unable to parse form content

### ISSUE THREAD

**Issue by codefox42** [scm-manager/scm-manager#2123]
### Bug Report

- I am trying to do a migration from 1.60 to 2.39.0 with 591 repositories (mostly Mercurial repositories, also a few Git repositories) based on the Docker image.
- Start the container with the image tagged with `2.39.0`
- Open the migration wizard in the browser
- Change the strategy for all repositories to `MOVE`
- Click `Submit`

As a result the following response is displayed immediately:

> **HTTP ERROR 400 Unable to parse form content**
>
> * **URI:** `/scm/`
> * **STATUS:** `400`
> * **MESSAGE:** `Unable to parse form content`
> * **SERVLET:** `default`
> * **CAUSED BY:** `org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content`
> * **CAUSED BY:** `java.lang.IllegalStateException: Form with too many keys [1001 > 1000]`
> 
>
> ```
> org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content
> 	at org.eclipse.jetty.server.Request.getParameters(Request.java:439)
> 	at org.eclipse.jetty.server.Request.getParameter(Request.java:1075)
> 	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194)
> 	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194)
> 	at sonia.scm.update.MigrationWizardServlet.doPost(MigrationWizardServlet.java:105)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
> 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
> 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
> 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
> 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
> 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
> 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
> 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
> 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException: Form with too many keys [1001 &gt; 1000]
> 	at org.eclipse.jetty.util.UrlEncoded.checkMaxKeys(UrlEncoded.java:699)
> 	at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:502)
> 	at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:572)
> 	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:582)
> 	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:531)
> 	at org.eclipse.jetty.server.Request.getParameters(Request.java:434)
> 	... 46 more
> ```
> 
> Powered by Jetty:// 9.4.44.v20210927

#### Describe your SCM-Manager setup

The SCM-Manager is executed in a stock Docker container (image: `scmmanager/scm-manager:2.39.0`) without a reverse proxy in between.

#### Which operating system, browser and versions do you use?

The migration was triggered from a Windows 11 host with a Chrome browser (version 105.0.5195.127).

#### Log of the bug

    scm_1  | 2022-09-26 08:51:35.521:WARN:oejs.Request:qtp1943325854-19: java.lang.IllegalStateException: Form with too many keys [1001 > 1000]
    scm_1  | 2022-09-26 08:51:35.524:WARN:oejs.HttpChannel:qtp1943325854-19: handleException /scm/ org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content

**Comment by codefox42** [comment]
I (re)discovered the hint in the [migration documentation](https://scm-manager.org/docs/2.39.x/en/migrate-scm-manager-from-v1/#huge-number-of-repositories) regarding huge number of repositories.
