### ISSUE TITLE
set permission

### ISSUE THREAD

**Issue by NikoForsaken** [scm-manager/scm-manager#2166]
**Issue description**
after migrating from version 1.60 to 2.2+, an error occurs when trying to add rights to a project
old permissions work, new ones are not added

**Describe how to reproduce the bug**
I open the repository, enter the user, assign rights, click submit
https://i.imgur.com/9Y9GxMD.png

**Describe your SCM-Manager setup**
Debian GNU/Linux 11, any browser
2022-12-22 12:41:58.090 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-activity-plugin@2.0.0
+- scm-branchwp-plugin@2.1.1
+- scm-git-plugin@2.40.1
+- scm-legacy-plugin@2.40.1
+- scm-hg-plugin@2.40.1
+- scm-content-search-plugin@1.2.1
+- scm-readme-plugin@2.0.3
+- scm-code-editor-plugin@1.0.1
   +- scm-editor-plugin@2.11.1
      +- scm-branchwp-plugin@2.1.1
      +- scm-pathwp-plugin@2.1.1
      +- scm-manage-folder-plugin@1.1.2
+- scm-groupmanager-plugin@2.0.1
+- scm-ssh-plugin@2.3.3
+- scm-ldap-plugin@2.5.0
+- scm-issuetracker-plugin@3.2.2
   +- scm-jira-plugin@3.1.3
+- scm-editor-plugin@2.11.1
   +- scm-branchwp-plugin@2.1.1
   +- scm-pathwp-plugin@2.1.1
   +- scm-manage-folder-plugin@1.1.2
+- scm-pathwp-plugin@2.1.1
+- scm-jira-plugin@3.1.3
+- scm-mail-plugin@2.9.0
   +- scm-branchwp-plugin@2.1.1
   +- scm-issuetracker-plugin@3.2.2
      +- scm-jira-plugin@3.1.3
+- scm-svn-plugin@2.40.1
+- scm-el-plugin@1.1.0
   +- scm-webhook-plugin@2.2.1
+- scm-webhook-plugin@2.2.1
+- scm-manage-folder-plugin@1.1.2

**Log of the bug**
2022-12-22 12:26:55.053 [qtp6738746-11] [CnTQjfvxPHv] INFO  sonia.scm.api.v2.resources.RepositoryPermissionRootResource - try to add new permission: RepositoryPermissionDto(name=ndokutovich, verbs=[], role=OWNER, groupPermission=false)
2022-12-22 12:26:55.065 [qtp6738746-11] [CnTQjfvxPHv] INFO  sonia.scm.repository.DefaultRepositoryManager - modify repository git/ART-PROMO (3eQtLKDW01) of type git
2022-12-22 12:26:55.071 [qtp6738746-11] [CnTQjfvxPHv] WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected java.lang.IllegalStateException to status code 500
java.lang.IllegalStateException: object is not valid
        at sonia.scm.util.AssertUtil.assertIsValid(AssertUtil.java:118)
        at sonia.scm.ManagerDaoAdapter.modify(ManagerDaoAdapter.java:47)

**Comment by pfeuffer** [comment]
Sorry for the late reply, somehow we missted your report during the holidays. We will take a look at it and come back to you.

**Comment by eheimbuch** [comment]
Hey @NikoForsaken,

could you check which e-mail address is used as contact for your repository. The error indicates that your repository object is invalid by the internal definition.

**Comment by nikoforsa** [comment]
nikoknv@gmail.com
nikolai.kuzmich@artezio.com

**Comment by nikoforsa** [comment]
2023-02-23 12:18:15.515 [qtp398110318-43] [CnTWg0rnaDN] WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected java.lang.IllegalStateException to status code 500
java.lang.IllegalStateException: object is not valid
        at sonia.scm.util.AssertUtil.assertIsValid(AssertUtil.java:118)
        at sonia.scm.ManagerDaoAdapter.modify(ManagerDaoAdapter.java:47)

**Comment by pfeuffer** [comment]
Hi @nikoforsa , those mail addresses look perfectly well, but ... are both set as contact in the repository (if this was even possible in v1)? SCM-Manager v2 only supports only one address as contact for a repository. Can you check this, please?

**Comment by nikoforsa** [comment]
where can i watch it?
https://i.imgur.com/vkKKlE6.png

**Comment by nikoforsa** [comment]
yes, this is bugs
if email contact at the begining with underline that error appears

**Comment by pfeuffer** [comment]
Thanks for this clarification, @nikoforsa . We will take a look at our validation and come back to you.

**Comment by nikoforsa** [comment]
https://i.imgur.com/tIjTHoq.png with an underscore at the beginning still doesn't work

**Comment by eheimbuch** [comment]
Hey @nikoforsa,

we just fixed this issue. The fix will be included in our next release.

Here the related commit: 
https://github.com/scm-manager/scm-manager/commit/7f0da3565984e6c7f4611291462cc3341756e10d
