### ISSUE TITLE
Subversion seems broken constant errors in logs

### ISSUE THREAD

**Issue by zaryabmustafa** [scm-manager/scm-manager#2191]
I usually get this error whenever I try to import a repository from an SVN dump file. Also second error occurs consistently.

I'm running this in a docker container.

2023-08-15 19:53:53.018 [CentralWorkQueue-1] [          ] ERROR sonia.scm.work.UnitOfWork - task sonia.scm.search.LuceneSimpleIndexTask@16334358 failed after 3.182 ms
sonia.scm.search.SearchEngineException: failed to open index at /var/lib/scm/index/repository/default
	at sonia.scm.search.IndexManager.openForWrite(IndexManager.java:105)
	at sonia.scm.search.LuceneIndexFactory.lambda$create$0(LuceneIndexFactory.java:56)
	at sonia.scm.search.SharableIndexWriter.open(SharableIndexWriter.java:55)
	at sonia.scm.search.LuceneIndex.open(LuceneIndex.java:65)
	at sonia.scm.search.LuceneIndex.<init>(LuceneIndex.java:61)
	at sonia.scm.search.LuceneIndexFactory.lambda$create$1(LuceneIndexFactory.java:54)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at sonia.scm.search.LuceneIndexFactory.create(LuceneIndexFactory.java:49)
	at sonia.scm.search.LuceneIndexTask.run(LuceneIndexTask.java:67)
	at sonia.scm.work.UnitOfWork.run(UnitOfWork.java:120)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: No such device: MMapIndexInput(path="/var/lib/scm/index/repository/default/segments_1") [this may be caused by lack of enough unfragmented virtual address space or too restrictive virtual memory limits enforced by the operating system, preventing us to map a chunk of 69 bytes. Please review 'ulimit -v', 'ulimit -m' (both should return 'unlimited'), and 'sysctl vm.max_map_count'. More information: http://blog.thetaphi.de/2012/07/use-lucenes-mmapdirectory-on-64bit.html]
	at java.base/sun.nio.ch.FileChannelImpl.map0(Native Method)
	at java.base/sun.nio.ch.FileChannelImpl.mapInternal(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.map(Unknown Source)
	at org.apache.lucene.store.MMapDirectory.map(MMapDirectory.java:267)
	at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:242)
	at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:157)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1037)
	at sonia.scm.search.IndexManager.openForWrite(IndexManager.java:103)
	... 12 common frames omitted

**Comment by christophloose** [comment]
Hi @zaryabmustafa 

could you please provide an example dump? This would help us to understand you problem and to investigate it.

Thanks!

**Comment by zaryabmustafa** [comment]
Hey @christophloose ,

[DLTn5Fr613.zip](https://github.com/scm-manager/scm-manager/files/12357397/DLTn5Fr613.zip)

Is this what you require? I used support plugin for this.

**Comment by christophloose** [comment]
@zaryabmustafa I think there is a misunderstanding. We will need an example repository
