### ISSUE TITLE
IllegalArgumentException: event handler not found

### ISSUE THREAD

**Issue by codefox42** [scm-manager/scm-manager#2196]
## Issue description

In the logs I am spotting multiple `IllegalArgumentException`s, saying `event handler not found`. See the full stack trace below for details. New exceptions appear after a few minutes and usually come in a group of about ten exceptions.

#### Describe how to reproduce the bug

I'm not sure - any hints for further analysis of the cause of the exceptions would be greatly appreciated.

#### Describe your SCM-Manager setup

* SCM-Manager `2.46.1` running in a Docker container behind a Traefik reverse proxy on a Ubuntu system
* Using customized Docker image based on `scmmanager/scm-manager:2.46.1` (with `server-config.xml` patched: `/Configure/New[@id='scm-webapp']/Set[@name='contextPath']` changed to `/`).
* Plugins:
  * Audit Log 1.0.0
  * Repository Size 1.0.0
  * SSH 2.3.3
  * Branch Write Protection 2.1.1
  * Group Manager 2.0.1
  * Mustache Documentation 1.0.0
  * OpenAPI 1.1.4
  * Landingpage 1.14.0
  * Readme 2.1.0
  * Legacy 2.46.1
  * CodeEditor 1.1.0
  * Expression Language 1.1.0
  * Mail 2.10.1
  * Git 2.46.1
  * Mercurial 2.46.1
  * Subersion 2.46.1
  * Direct Filelink 2.0.0
  * Editor 2.12.1
  * Repository Mirror Plugin 2.3.0
  * Review 2.30.1
  * Webhook 2.4.1

#### Log of the bug

    Exception in thread "ScmEventBus-1-5101" java.lang.IllegalArgumentException: event handler not found
      at com.github.legman.EventBus.removeEventHandler(EventBus.java:289)
      at com.github.legman.EventHandler.handleEvent(EventHandler.java:105)
      at com.github.legman.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:52)
      at com.github.legman.EventBus.dispatchSynchronous(EventBus.java:452)
      at com.github.legman.EventBus.lambda$dispatch$1(EventBus.java:444)
      at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
      at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.base/java.lang.Thread.run(Unknown Source)

**Comment by christophloose** [comment]
Hi @codefox42 

this is fixed with our recent release 2.47. 

https://scm-manager.org/download/

**Comment by codefox42** [comment]
Hi @christophloose, thank you very much - looks good!
