### ISSUE TITLE
any Plugin can't be upload

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#895]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/895) by Cédric Levasseur (Bitbucket: [Cedric Levasseur](https://bitbucket.org/Cedric Levasseur), ).**

----------------------------------------

Hello 
I'm tring to create a little plugin for scm-manager with the archetype :

```
#!sh

mvn archetype:generate   -DarchetypeGroupId=sonia.scm.maven   -DarchetypeArtifactId=scm-plugin-archetype   -DarchetypeVersion=1.50   -DarchetypeRepository=http://maven.scm-manager.org/nexus/content/groups/public

```

If the mvn scmp:run task run well, i can't deploy to my real server.

```
SEVERE: Mapped exception to response: 500 (Internal Server Error)
javax.ws.rs.WebApplicationException: com.sun.jersey.api.MessageException: A message body writer for Java class sonia.scm.api.rest.RestActionResult, and Java type class sonia.scm.api.rest.RestActionResult, and MIME media type text/html was not found.
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:284)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)



```

Please let me know a way to go against this bug.
Anyway, scm-manager is a great product ! Thanks

**Comment by sdorra** [comment]
The plugin mechanism in scm-manager 1.x is based on maven and has caused a lot of trouble. So we decided to completely rewrite the plugin management in version 2. Those problems should be no longer relevant for v2.
